Repository sofastack/sofa-boot, pull requests merged in 2018-09, with the labels that each got.

#199 Support whether component can be duplicated registered
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/component/impl/ComponentManagerImpl.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spi/component/AbstractComponent.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spi/component/ComponentInfo.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/component/impl/ComponentManagerImplTest.java
Labels: enhancement

#200 fix throw object
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/integration/invoke/DynamicJvmServiceProxyFinder.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/service/binding/JvmBindingAdapter.java
Labels: bug

#211 Manager starter and third-lib version.
  sofaboot-dependencies/pom.xml
Labels: enhancement

#205 Fix that SofaBootComponentHealthCheckInfo health status is influenced by HealthIndicator.
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/service/SofaBootReadinessCheckEndpoint.java
Labels: bug

#214 fix SofaModuleBeanFactoryPostProcessor no beandefinition bug
  isle-sofa-boot-starter/pom.xml
  isle-sofa-boot-starter/src/main/java/com/alipay/sofa/isle/spring/listener/SofaModuleBeanFactoryPostProcessor.java
Labels: bug

#216 Release 2.4.8
  healthcheck-sofa-boot-starter/pom.xml
  infra-sofa-boot-starter/pom.xml
  isle-sofa-boot-starter/pom.xml
  pom.xml
  runtime-sofa-boot-plugin/pom.xml
  runtime-sofa-boot-starter/pom.xml
  sofaboot-dependencies/pom.xml
  sofaboot-samples/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/README.md
  sofaboot-samples/sofaboot-sample-with-isle/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-consumer/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-facade/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-provider/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/sofa-boot-run/pom.xml
  sofaboot-samples/sofaboot-sample-with-isolation/pom.xml
  sofaboot-samples/sofaboot-sample-with-rpc/README.md
  sofaboot-samples/sofaboot-sample-with-rpc/pom.xml
  sofaboot-samples/sofaboot-sample/pom.xml
  test-sofa-boot-starter/pom.xml
Labels: upgrade

#218 Provide friendly notice when the property of spring.application.name is missing.
  infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/autoconfigure/SofaBootInfraAutoConfiguration.java
  infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/env/EnvironmentCustomizer.java
  isle-sofa-boot-starter/src/main/java/com/alipay/sofa/isle/constants/SofaModuleFrameworkConstants.java
  isle-sofa-boot-starter/src/main/java/com/alipay/sofa/isle/stage/AbstractPipelineStage.java
  isle-sofa-boot-starter/src/test/java/com/alipay/sofa/isle/DeploymentExceptionTest.java
Labels: enhancement

#222 Add friendly hint.
  isle-sofa-boot-starter/src/main/java/com/alipay/sofa/isle/stage/SpringContextInstallStage.java
Labels: enhancement

#219 Cherry pick fixed.
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/service/SofaBootReadinessCheckEndpoint.java
  healthcheck-sofa-boot-starter/src/test/resources/logback.xml
  infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/log/AllInfraLoggerFactoryTest.java
  infra-sofa-boot-starter/src/test/resources/logback.xml
  isle-sofa-boot-starter/pom.xml
  isle-sofa-boot-starter/src/main/java/com/alipay/sofa/isle/spring/listener/SofaModuleBeanFactoryPostProcessor.java
  isle-sofa-boot-starter/src/test/resources/logback.xml
  runtime-sofa-boot-starter/src/test/resources/logback.xml
Labels: enhancement

#221 Optimize auto-configuration.
  isle-sofa-boot-starter/src/main/java/com/alipay/sofa/isle/spring/configuration/SofaModuleAutoConfiguration.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spi/spring/SofaRuntimeContextAware.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/SofaRuntimeContextAwareProcessor.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/configuration/SofaRuntimeAutoConfiguration.java
Labels: enhancement

#225 Update to 2.4.9 snapshot
  healthcheck-sofa-boot-starter/pom.xml
  infra-sofa-boot-starter/pom.xml
  isle-sofa-boot-starter/pom.xml
  isle-sofa-boot-starter/src/main/java/com/alipay/sofa/isle/deployment/impl/AbstractDeploymentDescriptor.java
  pom.xml
  runtime-sofa-boot-plugin/pom.xml
  runtime-sofa-boot-starter/pom.xml
  sofaboot-dependencies/pom.xml
  sofaboot-samples/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/README.md
  sofaboot-samples/sofaboot-sample-with-isle/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-consumer/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-facade/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-provider/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/sofa-boot-run/pom.xml
  sofaboot-samples/sofaboot-sample-with-isolation/pom.xml
  sofaboot-samples/sofaboot-sample-with-rpc/README.md
  sofaboot-samples/sofaboot-sample-with-rpc/pom.xml
  sofaboot-samples/sofaboot-sample/pom.xml
  test-sofa-boot-starter/pom.xml
Labels: enhancement

#226 Manage zipkin version.
  sofaboot-dependencies/pom.xml
Labels: upgrade

#227 Add test case.
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/beans/FactoryBeanPostProcessor.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/integration/BeanPostProcessorTest.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/util/StateMessage.java
Labels: optimization

#223 Add callback ref and callback classname attribute.
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/api/annotation/SofaReferenceBinding.java
  runtime-sofa-boot-starter/src/test/resources/config/application.properties
Labels: enhancement
