Repository sofastack/sofa-boot, pull requests merged in 2018-07, with the labels that each got.

#114 upgrade version 2.4.2
  healthcheck-sofa-boot-starter/pom.xml
  infra-sofa-boot-starter/pom.xml
  isle-sofa-boot-starter/pom.xml
  pom.xml
  runtime-sofa-boot-starter/pom.xml
  sofaboot-dependencies/pom.xml
  sofaboot-samples/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-consumer/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-facade/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-provider/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/sofa-boot-run/pom.xml
  sofaboot-samples/sofaboot-sample-with-isolation/pom.xml
  sofaboot-samples/sofaboot-sample-with-rpc/pom.xml
  sofaboot-samples/sofaboot-sample/pom.xml
  test-sofa-boot-starter/pom.xml
Labels: Upgrade

#115 fix readme
  sofaboot-samples/sofaboot-sample-with-isle/README.md
  sofaboot-samples/sofaboot-sample-with-rpc/README.md
Labels: document

#121 upgrade ark & jarslink version
  sofaboot-dependencies/pom.xml
Labels: Upgrade

#124 Add sofa boot version info to banner.
  infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/constants/CommonMiddlewareConstants.java
  infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/env/EnvironmentCustomizer.java
  infra-sofa-boot-starter/src/main/resources/META-INF/spring.factories
  infra-sofa-boot-starter/src/main/resources/banner.txt
  runtime-sofa-boot-starter/pom.xml
Labels: optimization

#123 Unified using SofaBootLogSpaceIsolationInit.
  healthcheck-sofa-boot-starter/pom.xml
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/initializer/HealthCheckInitializer.java
  healthcheck-sofa-boot-starter/src/main/resources/META-INF/spring.factories
  runtime-sofa-boot-starter/pom.xml
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spi/log/SofaRuntimeLoggerFactory.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/initializer/SofaRuntimeSpringContextInitializer.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/ark/SofaEventHandlerTest.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/log/SofaRuntimeLoggerFactoryTest.java
Labels: optimization

#122 Using jackson instead of fastjson.
  healthcheck-sofa-boot-starter/pom.xml
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/configuration/HealthCheckConfiguration.java
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/core/AfterHealthCheckCallbackProcessor.java
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/core/ComponentCheckProcessor.java
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/core/HealthIndicatorCheckProcessor.java
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/core/SpringContextCheckProcessor.java
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/log/SofaBootHealthCheckLoggerFactory.java
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/startup/HealthCheckTrigger.java
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/startup/ReadinessCheckProcessor.java
Labels: optimization

#130 Remove AbstractSofaBootMiddlewareVersionFacade.
  infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/endpoint/SofaBootVersionEndpoint.java
  infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/standard/AbstractSofaBootMiddlewareVersionFacade.java
  infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/bean/SofaBootVersionImpl.java
  infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/bean/SofaRestVersionImpl.java
  infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/bean/SofaRpcVersionImpl.java
  infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/usercases/SofaBootVersionEndpointTest.java
  infra-sofa-boot-starter/src/test/resources/META-INF/sofa.versions.properties
  infra-sofa-boot-starter/src/test/resources/META-INF/sofaboot-web-test/infra-test.xml
Labels: remove

#132 ClientFactoryBeanPostProcessor implements PriorityOrdered.
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/ClientFactoryBeanPostProcessor.java
Labels: enhancement

#136 Upgrade version to 2.4.4-SNAPSHOT.
  healthcheck-sofa-boot-starter/pom.xml
  infra-sofa-boot-starter/pom.xml
  isle-sofa-boot-starter/pom.xml
  pom.xml
  runtime-sofa-boot-starter/pom.xml
  sofaboot-dependencies/pom.xml
  sofaboot-samples/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/README.md
  sofaboot-samples/sofaboot-sample-with-isle/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-consumer/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-facade/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-provider/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/sofa-boot-run/pom.xml
  sofaboot-samples/sofaboot-sample-with-isolation/pom.xml
  sofaboot-samples/sofaboot-sample-with-rpc/README.md
  sofaboot-samples/sofaboot-sample-with-rpc/pom.xml
  sofaboot-samples/sofaboot-sample/pom.xml
  test-sofa-boot-starter/pom.xml
Labels: upgrade

#139 Update maven-javadoc-plugin version to 2.10.1.(#133)
  pom.xml
Labels: upgrade

#141 Upgrade sofa-bolt version to 1.4.2
  sofaboot-dependencies/pom.xml
Labels: upgrade

#146 fix #145
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/startup/StartUpHealthCheckStatus.java
  healthcheck-sofa-boot-starter/src/test/java/com/alipay/sofa/healthcheck/readiness/ReadinessCheckProcessorTest.java
Labels: bug

#148 Upgrade 3.0.0-SNAPSHOT
  healthcheck-sofa-boot-starter/pom.xml
  infra-sofa-boot-starter/pom.xml
  isle-sofa-boot-starter/pom.xml
  pom.xml
  runtime-sofa-boot-starter/pom.xml
  sofaboot-dependencies/pom.xml
  sofaboot-samples/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/README.md
  sofaboot-samples/sofaboot-sample-with-isle/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-consumer/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-facade/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-provider/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/sofa-boot-run/pom.xml
  sofaboot-samples/sofaboot-sample-with-isolation/pom.xml
  sofaboot-samples/sofaboot-sample-with-rpc/README.md
  sofaboot-samples/sofaboot-sample-with-rpc/pom.xml
  sofaboot-samples/sofaboot-sample/pom.xml
  test-sofa-boot-starter/pom.xml
Labels: upgrade

#152 Remove sofa dependencies.
  .travis.yml
  pom.xml
  sofaboot-dependencies/pom.xml
Labels: refactor

#155 Switch com.alipay.sofa.healthcheck.readiness to com.alipay.sofa.healthcheck in order to keep the configuration style
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/configuration/SofaBootHealthCheckAutoConfiguration.java
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/service/SofaBootReadinessCheckEndpoint.java
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/service/SofaBootReadinessCheckMvcEndpoint.java
  healthcheck-sofa-boot-starter/src/test/java/com/alipay/sofa/healthcheck/usercases/HealthEndpointDisableConfigurationTest.java
Labels: optimization

#157 Add sofa-version-maven-plugin for SOFABoot starters.
  healthcheck-sofa-boot-starter/pom.xml
  infra-sofa-boot-starter/pom.xml
  isle-sofa-boot-starter/pom.xml
  runtime-sofa-boot-starter/pom.xml
Labels: bug

#154 SOFABoot add configuration com.alipay.sofa.healthcheck.enabled to disable readiness check
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/service/EndPointConfig.java
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/service/SofaBootReadinessCheckEndpoint.java
  healthcheck-sofa-boot-starter/src/test/java/com/alipay/sofa/healthcheck/base/AbstractTestBase.java
  healthcheck-sofa-boot-starter/src/test/java/com/alipay/sofa/healthcheck/base/SpringBootWebApplication.java
  healthcheck-sofa-boot-starter/src/test/java/com/alipay/sofa/healthcheck/enable/SofaBootReadinessCheckEnableTest.java
  healthcheck-sofa-boot-starter/src/test/java/com/alipay/sofa/healthcheck/enable/SofaBootReadinessCheckUnableTest.java
  healthcheck-sofa-boot-starter/src/test/resources/application-disable.properties
  healthcheck-sofa-boot-starter/src/test/resources/application.properties
Labels: bug

#158 Simplify usage of sofa version maven plugin.
  healthcheck-sofa-boot-starter/pom.xml
  infra-sofa-boot-starter/pom.xml
  isle-sofa-boot-starter/pom.xml
  pom.xml
  runtime-sofa-boot-starter/pom.xml
  test-sofa-boot-starter/pom.xml
Labels: optimization
