Repository sofastack/sofa-boot, pull requests merged in 2018-04, with the labels that each got.

#28 Fix readiness check http status code bug
  healthcheck-sofa-boot-starter/pom.xml
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/service/EndPointConfig.java
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/service/SofaBootReadinessCheckEndpoint.java
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/service/SofaBootReadinessCheckMvcEndpoint.java
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/startup/HealthCheckTrigger.java
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/startup/ReadinessCheckProcessor.java
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/startup/StartUpHealthCheckStatus.java
  healthcheck-sofa-boot-starter/src/test/java/com/alipay/sofa/healthcheck/readiness/DownHealthIndicataor.java
  healthcheck-sofa-boot-starter/src/test/java/com/alipay/sofa/healthcheck/readiness/ReadinessCheckHttpCodeTest.java
  healthcheck-sofa-boot-starter/src/test/java/com/alipay/sofa/healthcheck/readiness/ReadinessCheckProcessorTest.java
  infra-sofa-boot-starter/pom.xml
  infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/log/AllInfraLoggerFactoryTest.java
  pom.xml
  runtime-sofa-boot-starter/pom.xml
  sofaboot-dependencies/pom.xml
  test-sofa-boot-starter/pom.xml
Labels: bug

#29 Clean up code
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/core/HealthCheckerType.java
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/service/EndPointConfig.java
  healthcheck-sofa-boot-starter/src/test/java/com/alipay/sofa/healthcheck/readiness/DownHealthIndicataor.java
  healthcheck-sofa-boot-starter/src/test/java/com/alipay/sofa/healthcheck/readiness/DownHealthIndicator.java
  healthcheck-sofa-boot-starter/src/test/java/com/alipay/sofa/healthcheck/readiness/ReadinessCheckHttpCodeTest.java
  infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/initializer/SOFABootInfrastructureSpringContextInitializer.java
  infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/log/AllInfraLoggerFactoryTest.java
  infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/log/Log4j2InfraLoggerFactoryTest.java
  infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/log/Log4jInfraLoggerFactoryTest.java
  infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/log/LogbackRestLoggerFactoryTest.java
  infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/log/base/AbstractTestBase.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spi/binding/BindingAdapter.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spi/service/BindingConverter.java
Labels: enhancement

#39 Update SOFABoot version to v2.3.1.
  sofaboot-samples/sofaboot-sample-with-rpc/README.md
Labels: document
