Repository sofastack/sofa-boot, pull requests merged in 2018-08, with the labels that each got.

#169 Check whether it is neccessary when copy BeanPostProcessors and BeanFactoryPostProcessors from Root Application Context to SOFA Module
  isle-sofa-boot-starter/src/main/java/com/alipay/sofa/isle/loader/DynamicSpringContextLoader.java
  isle-sofa-boot-starter/src/test/java/com/alipay/sofa/isle/integration/IntegrationTest.java
  isle-sofa-boot-starter/src/test/java/com/alipay/sofa/isle/integration/SofaBootTestAutoConfiguration.java
  isle-sofa-boot-starter/src/test/java/com/alipay/sofa/isle/processor/SampleBeanPostProcessor.java
  isle-sofa-boot-starter/src/test/java/com/alipay/sofa/isle/scan/SampleService.java
  isle-sofa-boot-starter/src/test/java/com/alipay/sofa/isle/scan/SampleServiceImpl.java
  isle-sofa-boot-starter/src/test/resources/META-INF/spring/test-service.xml
  isle-sofa-boot-starter/src/test/resources/config/application.properties
Labels: bug

#172 Change Version 2.4.4.SNAPSHOT to 2.4.4 for release
  healthcheck-sofa-boot-starter/pom.xml
  infra-sofa-boot-starter/pom.xml
  isle-sofa-boot-starter/pom.xml
  pom.xml
  runtime-sofa-boot-starter/pom.xml
  sofaboot-dependencies/pom.xml
  sofaboot-samples/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/README.md
  sofaboot-samples/sofaboot-sample-with-isle/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-consumer/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-facade/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-provider/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/sofa-boot-run/pom.xml
  sofaboot-samples/sofaboot-sample-with-isolation/pom.xml
  sofaboot-samples/sofaboot-sample-with-rpc/README.md
  sofaboot-samples/sofaboot-sample-with-rpc/pom.xml
  sofaboot-samples/sofaboot-sample/pom.xml
  test-sofa-boot-starter/pom.xml
Labels: upgrade

#176 Upgrade version to 2.4.5-SNAPSHOT.
  healthcheck-sofa-boot-starter/pom.xml
  infra-sofa-boot-starter/pom.xml
  isle-sofa-boot-starter/pom.xml
  pom.xml
  runtime-sofa-boot-starter/pom.xml
  sofaboot-dependencies/pom.xml
  sofaboot-samples/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/README.md
  sofaboot-samples/sofaboot-sample-with-isle/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-consumer/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-facade/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-provider/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/sofa-boot-run/pom.xml
  sofaboot-samples/sofaboot-sample-with-isolation/pom.xml
  sofaboot-samples/sofaboot-sample-with-rpc/README.md
  sofaboot-samples/sofaboot-sample-with-rpc/pom.xml
  sofaboot-samples/sofaboot-sample/pom.xml
  test-sofa-boot-starter/pom.xml
Labels: upgrade

#177 SofaService annotation support concrete type without any interface.
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/ServiceAnnotationBeanPostProcessor.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/integration/IntegrationTest.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/integration/features/AwareTest.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/integration/features/ServiceWithoutInterface.java
Labels: enhancement

#178 SofaService annotation support spring aop.
  runtime-sofa-boot-starter/pom.xml
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/ServiceAnnotationBeanPostProcessor.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/integration/IntegrationTest.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/integration/aop/SampleServiceAspect.java
  runtime-sofa-boot-starter/src/test/resources/META-INF/spring/test-service.xml
Labels: bug

#189 Prepare to release.
  healthcheck-sofa-boot-starter/pom.xml
  infra-sofa-boot-starter/pom.xml
  isle-sofa-boot-starter/pom.xml
  pom.xml
  runtime-sofa-boot-plugin/pom.xml
  runtime-sofa-boot-starter/pom.xml
  sofaboot-dependencies/pom.xml
  sofaboot-samples/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/README.md
  sofaboot-samples/sofaboot-sample-with-isle/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-consumer/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-facade/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-provider/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/sofa-boot-run/pom.xml
  sofaboot-samples/sofaboot-sample-with-isolation/pom.xml
  sofaboot-samples/sofaboot-sample-with-rpc/README.md
  sofaboot-samples/sofaboot-sample-with-rpc/pom.xml
  sofaboot-samples/sofaboot-sample/pom.xml
  test-sofa-boot-starter/pom.xml
Labels: upgrade

#193 Change version 246
  healthcheck-sofa-boot-starter/pom.xml
  infra-sofa-boot-starter/pom.xml
  isle-sofa-boot-starter/pom.xml
  pom.xml
  runtime-sofa-boot-plugin/pom.xml
  runtime-sofa-boot-starter/pom.xml
  sofaboot-dependencies/pom.xml
  sofaboot-samples/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-consumer/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-facade/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-provider/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/sofa-boot-run/pom.xml
  sofaboot-samples/sofaboot-sample-with-isolation/pom.xml
  sofaboot-samples/sofaboot-sample-with-rpc/pom.xml
  sofaboot-samples/sofaboot-sample/pom.xml
  test-sofa-boot-starter/pom.xml
Labels: upgrade

#201 Upgrade version 2.4.6
  healthcheck-sofa-boot-starter/pom.xml
  infra-sofa-boot-starter/pom.xml
  isle-sofa-boot-starter/pom.xml
  pom.xml
  runtime-sofa-boot-plugin/pom.xml
  runtime-sofa-boot-starter/pom.xml
  sofaboot-dependencies/pom.xml
  sofaboot-samples/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/README.md
  sofaboot-samples/sofaboot-sample-with-isle/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-consumer/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-facade/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-provider/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/sofa-boot-run/pom.xml
  sofaboot-samples/sofaboot-sample-with-isolation/pom.xml
  sofaboot-samples/sofaboot-sample-with-rpc/README.md
  sofaboot-samples/sofaboot-sample-with-rpc/pom.xml
  sofaboot-samples/sofaboot-sample/pom.xml
  test-sofa-boot-starter/pom.xml
Labels: upgrade

#203 Degrade bolt version.
  healthcheck-sofa-boot-starter/pom.xml
  infra-sofa-boot-starter/pom.xml
  isle-sofa-boot-starter/pom.xml
  pom.xml
  runtime-sofa-boot-plugin/pom.xml
  runtime-sofa-boot-starter/pom.xml
  sofaboot-dependencies/pom.xml
  sofaboot-samples/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/README.md
  sofaboot-samples/sofaboot-sample-with-isle/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-consumer/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-facade/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-provider/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/sofa-boot-run/pom.xml
  sofaboot-samples/sofaboot-sample-with-isolation/pom.xml
  sofaboot-samples/sofaboot-sample-with-rpc/README.md
  sofaboot-samples/sofaboot-sample-with-rpc/pom.xml
  sofaboot-samples/sofaboot-sample/pom.xml
  test-sofa-boot-starter/pom.xml
Labels: upgrade

#204 Upgrade version to 2.4.8-SNAPSHOT.
  healthcheck-sofa-boot-starter/pom.xml
  infra-sofa-boot-starter/pom.xml
  isle-sofa-boot-starter/pom.xml
  pom.xml
  runtime-sofa-boot-plugin/pom.xml
  runtime-sofa-boot-starter/pom.xml
  sofaboot-dependencies/pom.xml
  sofaboot-samples/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/README.md
  sofaboot-samples/sofaboot-sample-with-isle/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-consumer/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-facade/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-provider/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/sofa-boot-run/pom.xml
  sofaboot-samples/sofaboot-sample-with-isolation/pom.xml
  sofaboot-samples/sofaboot-sample-with-rpc/README.md
  sofaboot-samples/sofaboot-sample-with-rpc/pom.xml
  sofaboot-samples/sofaboot-sample/pom.xml
  test-sofa-boot-starter/pom.xml
Labels: upgrade
