Repository sofastack/sofa-boot, pull requests merged in 2018-11, with the labels that each got.

#259 Fix logger linkage error.
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/initializer/SofaRuntimeSpringContextInitializer.java
Labels: bug

#267 Fix multi biz invocation.
  runtime-sofa-boot-plugin/pom.xml
Labels: bug

#269 Fix readiness check details lost
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/service/ReadinessEndpointWebExtension.java
  healthcheck-sofa-boot-starter/src/test/java/com/alipay/sofa/healthcheck/usercases/HealthEndpointDefaultConfigurationTest.java
Labels: bug

#268 Fix cloud compatible
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/core/AfterReadinessCheckCallbackProcessor.java
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/core/HealthCheckerProcessor.java
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/core/HealthIndicatorProcessor.java
  infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/constants/SofaBootInfraConstants.java
  infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/env/EnvironmentCustomizer.java
  infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/listener/SofaBootstrapRunListener.java
  infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/utils/BinaryOperators.java
  infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/utils/SOFABootEnvUtils.java
  infra-sofa-boot-starter/src/main/resources/META-INF/spring.factories
  infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/base/AbstractTestBase.java
  infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/base/SofaBootWebSpringBootApplication.java
  infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/usercases/VersionEndpointDisableConfigurationTest.java
  infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/utils/SOFABootEnvUtilsTest.java
  infra-sofa-boot-starter/src/test/resources/application.properties
Labels: bug

#271 Upgrade version to 3.0.0
  README.md
  healthcheck-sofa-boot-starter/pom.xml
  infra-sofa-boot-starter/pom.xml
  isle-sofa-boot-starter/pom.xml
  pom.xml
  runtime-sofa-boot-plugin/pom.xml
  runtime-sofa-boot-starter/pom.xml
  sofaboot-samples/pom.xml
  sofaboot-samples/sofaboot-sample-standard/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/README.md
  sofaboot-samples/sofaboot-sample-with-isle/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-consumer/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-facade/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-provider/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/sofa-boot-run/pom.xml
  sofaboot-samples/sofaboot-sample-with-isolation/pom.xml
  sofaboot-samples/sofaboot-sample-with-rpc/README.md
  sofaboot-samples/sofaboot-sample-with-rpc/pom.xml
  sofaboot-samples/sofaboot-sample/pom.xml
  test-sofa-boot-starter/pom.xml
Labels: upgrade

#264 Support placeholder in SofaService and SofaReference annotation.
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/annotation/PlaceHolderAnnotationInvocationHandler.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/annotation/PlaceHolderBinder.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/annotation/WrapperAnnotation.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/ServiceAnnotationBeanPostProcessor.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/annotation/AnnotationSample.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/annotation/AnnotationSampleTest.java
  runtime-sofa-boot-starter/src/test/resources/config/application-annotation.properties
Labels: enhancement

#274 Cherry pick bug fix from 3.x
  infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/constants/CommonMiddlewareConstants.java
  infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/listener/SofaBootstrapRunListener.java
  infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/utils/SOFABootEnvUtils.java
  infra-sofa-boot-starter/src/main/resources/META-INF/spring.factories
  infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/base/AbstractTestBase.java
  infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/utils/SOFABootEnvUtilsTest.java
  infra-sofa-boot-starter/src/test/resources/config/application.properties
  runtime-sofa-boot-plugin/pom.xml
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/initializer/SofaRuntimeSpringContextInitializer.java
Labels: bug

#275 Prepare to release 2.5.2
  healthcheck-sofa-boot-starter/pom.xml
  infra-sofa-boot-starter/pom.xml
  isle-sofa-boot-starter/pom.xml
  pom.xml
  runtime-sofa-boot-plugin/pom.xml
  runtime-sofa-boot-starter/pom.xml
  sofaboot-samples/pom.xml
  sofaboot-samples/sofaboot-sample-standard/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/README.md
  sofaboot-samples/sofaboot-sample-with-isle/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-consumer/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-facade/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-provider/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/sofa-boot-run/pom.xml
  sofaboot-samples/sofaboot-sample-with-isolation/pom.xml
  sofaboot-samples/sofaboot-sample-with-rpc/README.md
  sofaboot-samples/sofaboot-sample-with-rpc/pom.xml
  sofaboot-samples/sofaboot-sample/pom.xml
  test-sofa-boot-starter/pom.xml
Labels: upgrade

#280 Add serialize type in annotation
  healthcheck-sofa-boot-starter/pom.xml
  infra-sofa-boot-starter/pom.xml
  isle-sofa-boot-starter/pom.xml
  pom.xml
  runtime-sofa-boot-plugin/pom.xml
  runtime-sofa-boot-starter/pom.xml
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/api/annotation/SofaReferenceBinding.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/api/annotation/SofaServiceBinding.java
  test-sofa-boot-starter/pom.xml
Labels: enhancement

#282 Support placeholder in SofaService and SofaReference annotation. (#264)
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/annotation/PlaceHolderAnnotationInvocationHandler.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/annotation/PlaceHolderBinder.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/annotation/WrapperAnnotation.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/ServiceAnnotationBeanPostProcessor.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/annotation/AnnotationSample.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/annotation/AnnotationSampleTest.java
  runtime-sofa-boot-starter/src/test/resources/config/application-annotation.properties
Labels: enhancement

#284 Fix typo in comment
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/api/annotation/SofaServiceBinding.java
Labels: document
