Repository sofastack/sofa-boot, pull requests merged in 2018-12, with the labels that each got.

#302 Update SOFABoot version to 3.1.1-SNAPSHOT.
  healthcheck-sofa-boot-starter/pom.xml
  infra-sofa-boot-starter/pom.xml
  isle-sofa-boot-starter/pom.xml
  pom.xml
  runtime-sofa-boot-plugin/pom.xml
  runtime-sofa-boot-starter/pom.xml
  test-sofa-boot-starter/pom.xml
Labels: upgrade

#307 Fix compatible with spring boot
  isle-sofa-boot-starter/src/main/java/com/alipay/sofa/isle/loader/DynamicSpringContextLoader.java
  isle-sofa-boot-starter/src/test/java/com/alipay/sofa/isle/spring/health/SofaModuleHealthCheckerTest.java
  runtime-sofa-boot-starter/pom.xml
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/initializer/SofaRuntimeSpringContextInitializer.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/listener/SofaRuntimeApplicationListener.java
  runtime-sofa-boot-starter/src/main/resources/META-INF/spring.factories
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/ark/SofaEventHandlerTest.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/integration/TestSofaServiceAndReferenceException.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/integration/base/AbstractTestBase.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/integration/base/TestBase.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/spring/config/SofaRuntimePropertiesTest.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/spring/health/SofaComponentHealthCheckerTest.java
Labels: bug

#303 Add gradle plugin
  .gitignore
  pom.xml
  sofa-boot-gradle-plugin/build.gradle
  sofa-boot-gradle-plugin/gradle/wrapper/gradle-wrapper.jar
  sofa-boot-gradle-plugin/gradle/wrapper/gradle-wrapper.properties
  sofa-boot-gradle-plugin/gradlew
  sofa-boot-gradle-plugin/gradlew.bat
  sofa-boot-gradle-plugin/pom.xml
  sofa-boot-gradle-plugin/settings.gradle
  sofa-boot-gradle-plugin/src/main/java/com/alipay/sofa/boot/gradle/plugin/Marker.java
  sofa-boot-gradle-plugin/src/main/java/org/springframework/boot/gradle/plugin/SofaBootPlugin.java
  sofa-boot-gradle-plugin/src/main/java/org/springframework/boot/gradle/plugin/SofaDependencyManagementPluginAction.java
  sofa-boot-gradle-plugin/src/main/resources/META-INF/gradle-plugins/com.alipay.sofa.boot.properties
  sofa-boot-gradle-plugin/src/test/java/com/alipay/sofa/boot/gradle/plugin/DependencyManagementPluginActionIntegrationTests.java
  sofa-boot-gradle-plugin/src/test/java/org/springframework/boot/gradle/junit/GradleCompatibilitySuite.java
  sofa-boot-gradle-plugin/src/test/java/org/springframework/boot/gradle/testkit/Dsl.java
  sofa-boot-gradle-plugin/src/test/java/org/springframework/boot/gradle/testkit/GradleBuild.java
  sofa-boot-gradle-plugin/src/test/resources/com/alipay/sofa/boot/gradle/plugin/DependencyManagementPluginActionIntegrationTests.gradle
Labels: enhancement

#317 Optimize log configuration and strictly depend on log-sofa-boot-starter
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/initializer/SofaBootHealthCheckInitializer.java
  infra-sofa-boot-starter/pom.xml
  infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/constants/SofaBootInfraConstants.java
  infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/initializer/SOFABootInfrastructureSpringContextInitializer.java
  infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/listener/SofaBootstrapRunListener.java
  infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/log/space/SofaBootLogSpaceIsolationInit.java
  infra-sofa-boot-starter/src/main/resources/com/alipay/sofa/infra/log/log4j2/log-conf.xml
  infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/log/Log4j2InfraLoggerFactoryTest.java
  infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/log/LogbackRestLoggerFactoryTest.java
  infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/log/base/AbstractTestBase.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/initializer/SofaRuntimeSpringContextInitializer.java
Labels: enhancement

#319 Prepare to release
  healthcheck-sofa-boot-starter/pom.xml
  infra-sofa-boot-starter/pom.xml
  isle-sofa-boot-starter/pom.xml
  pom.xml
  runtime-sofa-boot-plugin/pom.xml
  runtime-sofa-boot-starter/pom.xml
  test-sofa-boot-starter/pom.xml
Labels: upgrade

#323 Upgrade SOFA Gradle Plugin version
  sofa-boot-gradle-plugin/build.gradle
  sofa-boot-gradle-plugin/pom.xml
Labels: upgrade
