Repository sofastack/sofa-boot, pull requests merged in 2019-10, with the labels that each got.

#500 Fix Unable to generate a executable jar after 3.2.0
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: bug, cla:yes, size/XS

#489 Update ark version 1.1.0 snapshot
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-plugins/rpc-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-plugins/runtime-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-plugins/tracer-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
  sofa-boot-samples/pom.xml
  sofa-boot-samples/sofaboot-samples/pom.xml
  sofa-boot-samples/sofaboot-samples/sofaboot-sample-with-isolation/pom.xml
Labels: cla:yes, size/M

#507 Shutdown RuntimeShutdownAware first
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/component/impl/StandardSofaRuntimeManager.java
Labels: cla:yes, size/XS

#511 fix skip jvm invoke
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/invoke/DynamicJvmServiceProxyFinder.java
Labels: bug, cla:yes, size/M

#513 Support find service target from other biz
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/component/ReferenceComponent.java
Labels: cla:yes, size/XS
