Repository sofastack/sofa-boot, pull requests merged in 2019-01, with the labels that each got.

#322 Chang CI coverage tool
  .travis.yml
Labels: optimization

#321 Add SOFARPC annotation config
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/api/annotation/SofaReferenceBinding.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/api/annotation/SofaServiceBinding.java
Labels: enhancement

#315 pick 2.4.8 lost code
  isle-sofa-boot-starter/src/main/java/com/alipay/sofa/isle/loader/DynamicSpringContextLoader.java
  isle-sofa-boot-starter/src/main/java/com/alipay/sofa/isle/spring/factory/BeanLoadCostBeanFactory.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/component/impl/ComponentManagerImpl.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spi/component/ComponentManager.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spi/log/SofaLogger.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/factory/AbstractContractFactoryBean.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/factory/ReferenceFactoryBean.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/factory/ServiceFactoryBean.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/parser/AbstractContractDefinitionParser.java
Labels: bug

#329 Suport full annotation style
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/initializer/SofaBootHealthCheckInitializer.java
  infra-sofa-boot-starter/pom.xml
  infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/constants/CommonMiddlewareConstants.java
  infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/initializer/SOFABootInfrastructureSpringContextInitializer.java
  infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/listener/SofaBootstrapRunListener.java
  infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/log/space/SofaBootLogSpaceIsolationInit.java
  infra-sofa-boot-starter/src/main/resources/com/alipay/sofa/infra/log/log4j2/log-conf.xml
  infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/log/Log4j2InfraLoggerFactoryTest.java
  infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/log/LogbackRestLoggerFactoryTest.java
  infra-sofa-boot-starter/src/test/java/com/alipay/sofa/infra/log/base/AbstractTestBase.java
  isle-sofa-boot-starter/src/main/java/com/alipay/sofa/isle/loader/DynamicSpringContextLoader.java
  isle-sofa-boot-starter/src/test/java/com/alipay/sofa/isle/ReferenceAnnotationBeanPostProcessorTest.java
  isle-sofa-boot-starter/src/test/java/com/alipay/sofa/isle/ServiceAnnotationBeanPostProcessorTest.java
  isle-sofa-boot-starter/src/test/java/com/alipay/sofa/isle/spring/health/SofaModuleHealthCheckerTest.java
  runtime-sofa-boot-starter/pom.xml
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/api/annotation/SofaReference.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/api/annotation/SofaService.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/ReferenceAnnotationBeanPostProcessor.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/ServiceBeanFactoryPostProcessor.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/bean/SofaBeanNameGenerator.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/bean/SofaParameterNameDiscoverer.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/configuration/SofaRuntimeAutoConfiguration.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/factory/AbstractContractFactoryBean.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/factory/ServiceFactoryBean.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/initializer/SofaRuntimeSpringContextInitializer.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/parser/AbstractContractDefinitionParser.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/parser/ReferenceDefinitionParser.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/parser/ServiceDefinitionParser.java
  runtime-sofa-boot-starter/src/main/resources/META-INF/spring.factories
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/ark/SofaEventHandlerTest.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/beans/impl/MethodBeanClassAnnotationSampleService.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/beans/impl/MethodBeanMethodAnnotationSampleService.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/beans/impl/ParameterAnnotationSampleService.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/beans/impl/XmlAnnotationSampleService.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/integration/IntegrationTest.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/integration/TestSofaServiceAndReferenceException.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/integration/base/AbstractTestBase.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/integration/base/MultiSofaReferenceConfiguration.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/integration/base/MultiSofaServiceConfiguration.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/integration/base/TestBase.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/integration/features/AwareTest.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/spring/config/SofaRuntimePropertiesTest.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/spring/health/SofaComponentHealthCheckerTest.java
  runtime-sofa-boot-starter/src/test/resources/META-INF/spring.factories
  runtime-sofa-boot-starter/src/test/resources/META-INF/spring/test-service.xml
Labels: enhancement

#334 fix#333
  isle-sofa-boot-starter/src/main/java/com/alipay/sofa/isle/loader/DynamicSpringContextLoader.java
Labels: enhancement

#325 Healthcheck management fix
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/configuration/HealthCheckConstants.java
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/service/SofaBootHealthIndicator.java
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/service/SofaBootReadinessCheckEndpoint.java
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/service/SofaBootReadinessCheckMvcEndpoint.java
  healthcheck-sofa-boot-starter/src/main/java/com/alipay/sofa/healthcheck/startup/ReadinessCheckListener.java
  healthcheck-sofa-boot-starter/src/test/java/com/alipay/sofa/healthcheck/management/HealthCheckManagementTest.java
  healthcheck-sofa-boot-starter/src/test/java/com/alipay/sofa/healthcheck/management/HighOrderApplicationListener.java
  healthcheck-sofa-boot-starter/src/test/resources/config/application-management.properties
Labels: bug

#335 add missing apiType logic
  .gitignore
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/factory/AbstractContractFactoryBean.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/integration/IntegrationTest.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/integration/TestSofaServiceAndReferenceException.java
Labels: bug

#337 support async init
  .travis.yml
  infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/config/spring/namespace/handler/SofaBootNamespaceHandler.java
  infra-sofa-boot-starter/src/main/java/com/alipay/sofa/infra/constants/CommonMiddlewareConstants.java
  infra-sofa-boot-starter/src/main/resources/META-INF/com/alipay/sofa/infra/config/spring/namespace/schema/rpc.xsd
  isle-sofa-boot-starter/src/test/java/com/alipay/sofa/isle/spring/parser/AsyncInitBeanDefinitionDecoratorTest.java
  pom.xml
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/AsyncProxyBeanPostProcessor.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/async/AsyncInitBeanHolder.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/async/AsyncTaskExecutionListener.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/async/AsyncTaskExecutor.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/config/SofaRuntimeConfigurationProperties.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/configuration/SofaRuntimeAutoConfiguration.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/spring/parser/AsyncInitBeanDefinitionDecorator.java
  runtime-sofa-boot-starter/src/main/java/com/alipay/sofa/runtime/util/NamedThreadFactory.java
  runtime-sofa-boot-starter/src/main/resources/META-INF/services/com.alipay.sofa.infra.config.spring.namespace.spi.SofaBootTagNameSupport
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/beans/TimeWasteBean.java
  runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/integration/AsyncInitTest.java
  runtime-sofa-boot-starter/src/test/resources/META-INF/async/async-test.xml
Labels: enhancement

#348 Upgrade version
  README.md
  change_version.sh
  healthcheck-sofa-boot-starter/pom.xml
  infra-sofa-boot-starter/pom.xml
  isle-sofa-boot-starter/pom.xml
  pom.xml
  runtime-sofa-boot-plugin/pom.xml
  runtime-sofa-boot-starter/pom.xml
  sofaboot-samples/pom.xml
  sofaboot-samples/sofaboot-sample-standard/app/biz/service-impl/pom.xml
  sofaboot-samples/sofaboot-sample-standard/app/biz/shared/pom.xml
  sofaboot-samples/sofaboot-sample-standard/app/common/dal/pom.xml
  sofaboot-samples/sofaboot-sample-standard/app/common/service/facade/pom.xml
  sofaboot-samples/sofaboot-sample-standard/app/test/pom.xml
  sofaboot-samples/sofaboot-sample-standard/app/web/pom.xml
  sofaboot-samples/sofaboot-sample-standard/app/web/src/main/java/com/alipay/sofa/controller/SampleRestController.java
  sofaboot-samples/sofaboot-sample-standard/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-consumer/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-facade/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-provider/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/sofa-boot-run/pom.xml
  sofaboot-samples/sofaboot-sample-with-isolation/pom.xml
  sofaboot-samples/sofaboot-sample-with-rpc/pom.xml
  sofaboot-samples/sofaboot-sample/pom.xml
  test-sofa-boot-starter/pom.xml
Labels: upgrade

#341 Update samples
  sofaboot-samples/sofaboot-sample-standard/app/test/src/test/java/com/alipay/sofa/test/base/AbstractTestBase.java
  sofaboot-samples/sofaboot-sample-standard/app/web/src/main/java/com/alipay/sofa/controller/SampleRestController.java
  sofaboot-samples/sofaboot-sample-with-isle/sofa-boot-run/pom.xml
Labels: optimization

#354 Update version
  .travis.yml
  change_version.sh
  healthcheck-sofa-boot-starter/pom.xml
  infra-sofa-boot-starter/pom.xml
  isle-sofa-boot-starter/pom.xml
  pom.xml
  runtime-sofa-boot-plugin/pom.xml
  runtime-sofa-boot-starter/pom.xml
  sofa-boot-gradle-plugin/build.gradle
  sofa-boot-gradle-plugin/pom.xml
  sofaboot-samples/pom.xml
  sofaboot-samples/sofaboot-sample-standard/app/biz/service-impl/pom.xml
  sofaboot-samples/sofaboot-sample-standard/app/biz/shared/pom.xml
  sofaboot-samples/sofaboot-sample-standard/app/common/dal/pom.xml
  sofaboot-samples/sofaboot-sample-standard/app/common/service/facade/pom.xml
  sofaboot-samples/sofaboot-sample-standard/app/test/pom.xml
  sofaboot-samples/sofaboot-sample-standard/app/web/pom.xml
  sofaboot-samples/sofaboot-sample-standard/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/README.md
  sofaboot-samples/sofaboot-sample-with-isle/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-consumer/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-facade/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/service-provider/pom.xml
  sofaboot-samples/sofaboot-sample-with-isle/sofa-boot-run/pom.xml
  sofaboot-samples/sofaboot-sample-with-isolation/pom.xml
  sofaboot-samples/sofaboot-sample-with-rpc/README.md
  sofaboot-samples/sofaboot-sample-with-rpc/pom.xml
  sofaboot-samples/sofaboot-sample/pom.xml
  test-sofa-boot-starter/pom.xml
Labels: upgrade
