Repository sofastack/sofa-boot, pull requests merged in 2019-08, with the labels that each got.

#462 Add tracer plugin back
  sofa-boot-project/sofa-boot-starters/tracer-sofa-boot-starter/pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/S

#466 update bolt version to 1.5.6
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/XS

#468 Fix sofaboot version not display
  sofa-boot-project/sofa-boot/pom.xml
Labels: bug, cla:yes, size/S

#469 update rpc 5.6.1 snapshot
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/XS

#456 Provide specified version invoke
  .travis.yml
  sofa-boot-project/sofa-boot-actuator-autoconfigure/src/test/resources/config/application.properties
  sofa-boot-project/sofa-boot-autoconfigure/src/test/java/com/alipay/sofa/autoconfigure/test/runtime/SofaRuntimePropertiesTest.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/SofaRuntimeProperties.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/configure/SofaRuntimeConfigurationProperties.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/invoke/DynamicJvmServiceProxyFinder.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/SofaEventHandlerTest.java
  sofa-boot-project/sofa-boot-plugins/rpc-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-plugins/runtime-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-plugins/tracer-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-starters/rpc-sofa-boot-starter/pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
  sofa-boot-samples/sofaboot-samples/sofaboot-sample-standard/app/test/src/test/java/com/alipay/sofa/test/base/AbstractTestBase.java
  sofa-boot-samples/sofaboot-samples/sofaboot-sample-with-isolation/pom.xml
  sofa-boot-samples/sofarpc-samples/pom.xml
  sofa-boot-samples/sofatracer-samples/tracer-sample-with-dubbo/tracer-sample-with-dubbo-consumer/pom.xml
  sofa-boot-samples/sofatracer-samples/tracer-sample-with-dubbo/tracer-sample-with-dubbo-provider/pom.xml
Labels: cla:yes, size/L

#471 fix classloader in ark
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/runtime/SofaRuntimeAutoConfiguration.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/stage/AbstractPipelineStage.java
Labels: bug, cla:yes, size/XS

#472 do not dependency on ark spi when not in ark env
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/invoke/DynamicJvmServiceProxyFinder.java
  sofa-boot-project/sofa-boot-starters/runtime-sofa-boot-starter/pom.xml
Labels: cla:yes, question, size/S
