Repository sofastack/sofa-boot, pull requests merged in 2019-09, with the labels that each got.

#493 Update README.md
  README.md
Labels: cla:yes, size/S

#495 Upgrade fastjson and jackson
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/XS

#490 update runtime plugin upon 3.2.0 and above
  sofa-boot-project/sofa-boot-plugins/runtime-sofa-boot-plugin/pom.xml
Labels: cla:yes, size/M

#488 fix dynamic invoke
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/invoke/DynamicJvmServiceProxyFinder.java
Labels: bug, cla:yes, size/XS
