Repository sofastack/sofa-boot, pull requests merged in 2019-11, with the labels that each got.

#515 use StringBuilder instead of StringBuffer in single-threaded local variable
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/container/ProviderConfigContainer.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/common/xmap/Path.java
Labels: cla:yes, size/XS

#517 Add Spring configuration metadata files back
  codecov.yml
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/ConfigurationMetaTest.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/ConfigurationMetaTest.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/ConfigurationMetaTest.java
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/src/test/com/alipay/sofa/tracer/boot/ConfigurationMetaTest.java
Labels: bug, cla:yes, size/L

#525 chore:make method protected
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/converter/RpcBindingConverter.java
Labels: cla:yes, size/M

#521 fix *postProcessors inherited problem (#442)
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/isle/SofaModuleAutoConfiguration.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/spring/listener/SofaModuleBeanFactoryPostProcessor.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/spring/share/SofaModulePostProcessorShareFilter.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/spring/share/SofaModulePostProcessorShareManager.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/spring/share/UnshareSofaModulePostProcessor.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/FailModuleTest.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/resources/config/application.properties
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/ServiceBeanFactoryPostProcessor.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/constant/SofaBootConstants.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/util/BeanDefinitionUtil.java
  sofa-boot-samples/sofaboot-samples/sofaboot-sample-with-isle/sofa-boot-run/src/test/java/com/alipay/sofa/isle/sample/test/processor/PostProcessorShareTest.java
Labels: First-time contributor, bug, cla:yes, size/XL

#526 Chore/optimize auto configuration rpc
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/SofaRpcAutoConfiguration.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/param/RpcBindingParam.java
Labels: cla:yes, size/M

#527 chore:update hessian 3.3.7 snapshot
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/XS

#528 chore:update sofarpc 5.6.3 snapshot
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/XS

#535 feat:update rest dep to 3.6.3
  sofa-boot-project/sofa-boot-starters/rpc-sofa-boot-starter/pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/L

#519 change-to-support-ark-event-profile
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/SofaBizHealthCheckEventHandler.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/SofaBizUninstallEventHandler.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/SofaEventHandlerTest.java
  sofa-boot-project/sofa-boot-plugins/runtime-sofa-boot-plugin/src/main/java/com/alipay/sofa/runtime/ark/plugin/SofaRuntimeActivator.java
Labels: cla:yes, size/L

#536 support invoke ark jvm service at startup phase
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/invoke/DynamicJvmServiceProxyFinder.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/FinishStartupEventHandler.java
  sofa-boot-project/sofa-boot-plugins/runtime-sofa-boot-plugin/src/main/java/com/alipay/sofa/runtime/ark/plugin/SofaRuntimeActivator.java
Labels: cla:yes, size/M

#537 support invoke ark jvm service at startup phase
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/invoke/DynamicJvmServiceProxyFinder.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/SofaEventHandlerTest.java
Labels: cla:yes, size/XS

#539 feat:reform the start listener to extend
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/SofaRpcAutoConfiguration.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/context/SofaBootRpcStartListener.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/SofaRpcTestAutoConfiguration.java
Labels: cla:yes, size/M
