Repository sofastack/sofa-boot, pull requests merged in 2020-12, with the labels that each got.

#770 Use Maven Action instead of travis-ci
  .github/workflows/maven.yml
  .travis.yml
  README.md
Labels: cla:yes, size/M

#771 Fix grammar and bugfix for tree display for bean load cost
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/spring/factory/BeanLoadCostBeanFactory.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/stage/ModuleLogOutputStage.java
Labels: bug, cla:yes, size/S

#772 Support for automatically console logging when local developing
  sofa-boot-project/sofa-boot-core/log-sofa-boot/src/main/java/com/alipay/sofa/boot/logging/LocalEnvUtil.java
  sofa-boot-project/sofa-boot-core/log-sofa-boot/src/main/java/com/alipay/sofa/boot/logging/LogEnvironmentPreparingListener.java
  sofa-boot-project/sofa-boot-core/log-sofa-boot/src/test/java/com/alipay/sofa/boot/logging/LocalEnvUtilTest.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/async/AsyncTaskExecutionListener.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/resources/com/alipay/sofa/runtime/log/log4j/config.properties
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/resources/com/alipay/sofa/runtime/log/log4j2/config.properties
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/resources/com/alipay/sofa/runtime/log/logback/config.properties
Labels: cla:yes, question, size/M

#775 update sofa-common-tools to 1.3.0-SNAPSHOT
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes

#779 3.6.0-SNAPSHOT and some refinement
  pom.xml
  sofa-boot-project/pom.xml
  sofa-boot-project/sofa-boot-actuator-autoconfigure/pom.xml
  sofa-boot-project/sofa-boot-actuator/pom.xml
  sofa-boot-project/sofa-boot-autoconfigure/pom.xml
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/stage/SpringContextInstallStage.java
  sofa-boot-project/sofa-boot-core/log-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/pom.xml
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/async/AsyncTaskExecutor.java
  sofa-boot-project/sofa-boot-core/startup-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/test-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-parent/pom.xml
  sofa-boot-project/sofa-boot-plugins/pom.xml
  sofa-boot-project/sofa-boot-plugins/rpc-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-plugins/runtime-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-plugins/tracer-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-starters/healthcheck-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/infra-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/isle-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/pom.xml
  sofa-boot-project/sofa-boot-starters/rpc-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/runtime-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/startup-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/test-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/tracer-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-tools/pom.xml
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/build.gradle
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/pom.xml
  sofa-boot-project/sofa-boot/pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/L

#781 Remove default profile activation and add grpc version management
  .github/workflows/maven.yml
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/M

#786 add config source to SofaConfigs
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/listener/SofaConfigSourceSupportListener.java
  sofa-boot-project/sofa-boot/src/main/resources/META-INF/spring.factories
  sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/test/lisener/SofaConfigSourceSupportListenerTest.java
  sofa-boot-project/sofa-boot/src/test/resources/application.properties
Labels: cla:yes, size/L

#787 Remove infra starter
  sofa-boot-project/sofa-boot-starters/infra-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes

#788 Use Orded in ReadinessCheckListener
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/ReadinessCheckListener.java
Labels: cla:yes, size/XS

#790 Rpc-starter use sofa-common-tools's SofaConfig instead of System.getProperty
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/logging.path_IS_UNDEFINED/rpc/triple-threadpool.log
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/config/SofaBootRpcConfigKeys.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/container/RegistryConfigContainer.java
Labels: cla:yes, size/M

#793 Chore/common tools
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/src/test/java/com/alipay/sofa/common/boot/logging/test/LogTestBase.java
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/S
