Repository sofastack/sofa-boot, pull requests merged in 2020-01, with the labels that each got.

#547 Update spring.factories
  sofa-boot-project/sofa-boot-autoconfigure/src/main/resources/META-INF/spring.factories
Labels: First-time contributor, cla:yes, size/S

#572 upgrade version 3.2.2-SNAPSHOT
  pom.xml
  sofa-boot-project/pom.xml
  sofa-boot-project/sofa-boot-actuator-autoconfigure/pom.xml
  sofa-boot-project/sofa-boot-actuator/pom.xml
  sofa-boot-project/sofa-boot-autoconfigure/pom.xml
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/log-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/pom.xml
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/test-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-parent/pom.xml
  sofa-boot-project/sofa-boot-plugins/pom.xml
  sofa-boot-project/sofa-boot-plugins/rpc-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-plugins/runtime-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-plugins/tracer-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-starters/healthcheck-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/infra-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/isle-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/pom.xml
  sofa-boot-project/sofa-boot-starters/rpc-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/runtime-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/test-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/tracer-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-tools/pom.xml
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/build.gradle
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/pom.xml
  sofa-boot-project/sofa-boot/pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/M

#574 Update Spring Boot version
  sofa-boot-project/sofa-boot-actuator-autoconfigure/src/test/java/com/alipay/sofa/actuator/autoconfigure/test/listener/HighOrderApplicationListener.java
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/build.gradle
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/M

#567 fix:fix the bug of registry config
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/SofaRpcAutoConfiguration.java
Labels: bug, cla:yes, size/XS

#573 remove jaxrs api
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/S

#577 Change order of ReadinessCheckListener to LOWEST_PRECEDENCE
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/ReadinessCheckListener.java
Labels: cla:yes, size/XS

#576 Change order of ReadinessCheckListener to LOWEST_PRECEDENCE
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/ReadinessCheckListener.java
Labels: cla:yes, size/XS

#578 remove jaxrs api
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/S

#580 Removing register system beanPostProcessor
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/RuntimeContextBeanFactoryPostProcessor.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/BeanPostProcessorOrderTest.java
Labels: cla:yes, size/S

#582 upgrade version 3.2.2
  pom.xml
  sofa-boot-project/pom.xml
  sofa-boot-project/sofa-boot-actuator-autoconfigure/pom.xml
  sofa-boot-project/sofa-boot-actuator/pom.xml
  sofa-boot-project/sofa-boot-autoconfigure/pom.xml
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/log-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/pom.xml
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/test-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-parent/pom.xml
  sofa-boot-project/sofa-boot-plugins/pom.xml
  sofa-boot-project/sofa-boot-plugins/rpc-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-plugins/runtime-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-plugins/tracer-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-starters/healthcheck-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/infra-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/isle-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/pom.xml
  sofa-boot-project/sofa-boot-starters/rpc-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/runtime-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/test-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/tracer-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-tools/pom.xml
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/build.gradle
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/pom.xml
  sofa-boot-project/sofa-boot/pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/M

#585 Add root Spring context to SofaRuntimeManager
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/runtime/SofaRuntimeAutoConfiguration.java
  sofa-boot-project/sofa-boot-autoconfigure/src/test/java/com/alipay/sofa/autoconfigure/test/runtime/SofaRuntimeManagerTest.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/container/SpringBridge.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/component/impl/StandardSofaRuntimeManager.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spi/component/SofaRuntimeManager.java
Labels: cla:yes, size/M
