Repository sofastack/sofa-boot, pull requests merged in 2020-06, with the labels that each got.

#654 fix:fix adpater of unexport
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/adapter/RpcBindingAdapter.java
Labels: bug, cla:yes, size/S

#659 Fix application close before component manager shutdown
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/component/impl/StandardSofaRuntimeManager.java
Labels: bug, cla:yes, size/S

#658 feat:bolt process in io thread
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/config/SofaBootRpcProperties.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/container/ServerConfigContainer.java
Labels: cla:yes, size/S

#660 component health check display failed first
  sofa-boot-project/sofa-boot-actuator-autoconfigure/src/main/java/com/alipay/sofa/boot/actuator/autoconfigure/health/SofaBootHealthCheckAutoConfiguration.java
  sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/health/ComponentHealthIndicator.java
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/impl/ComponentHealthChecker.java
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/test/java/com/alipay/sofa/healthcheck/test/HealthCheckerProcessorTest.java
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/test/java/com/alipay/sofa/healthcheck/test/TestComponent.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/aware/DefaultRuntimeShutdownAware.java
Labels: cla:yes, size/L

#661 remove usage of javafx
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/impl/ComponentHealthChecker.java
Labels: cla:yes, size/L

#662 chore:update sofa rpc 5.7.3 snapshot
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/XS

#663 feat:update protobuf-java 3.11.0 to match protoc
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/XS

#666 update fastjson to 1.2.69
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/XS
