Repository sofastack/sofa-boot, pull requests merged in 2020-11, with the labels that each got.

#752 Update "Ant Financial Services Group" to "Ant Group"
  LICENSE
  sofa-boot-project/sofa-boot/src/main/resources/banner.txt
Labels: cla:yes, size/XS

#755 fix bean display problem
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/stage/ModuleLogOutputStage.java
Labels: bug, cla:yes, size/S

#753 Update sample description in readme
  README.md
Labels: cla:yes, size/XS

#754 Add developer and change organization name
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/S

#756 Add developer
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/XS

#758 export warn log when SofaReference annotation write on static field
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/ReferenceAnnotationBeanPostProcessor.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/SofaServiceAndReferenceTest.java
Labels: cla:yes, size/M

#760 Refactor using of sofa-common-tools and support for console logging
  sofa-boot-project/sofa-boot-core/log-sofa-boot/src/main/java/com/alipay/sofa/boot/logging/CommonLoggingApplicationListener.java
  sofa-boot-project/sofa-boot-core/log-sofa-boot/src/main/java/com/alipay/sofa/boot/logging/DefaultReInitializerChecker.java
  sofa-boot-project/sofa-boot-core/log-sofa-boot/src/main/java/com/alipay/sofa/boot/logging/LogEnvironmentPreparingListener.java
  sofa-boot-project/sofa-boot-core/log-sofa-boot/src/main/java/com/alipay/sofa/boot/logging/Mark.java
  sofa-boot-project/sofa-boot-core/log-sofa-boot/src/main/java/com/alipay/sofa/boot/logging/filter/DefaultLog4j2FilterGenerator.java
  sofa-boot-project/sofa-boot-core/log-sofa-boot/src/main/java/com/alipay/sofa/boot/logging/filter/DefaultLogbackFilterGenerator.java
  sofa-boot-project/sofa-boot-core/log-sofa-boot/src/main/java/com/alipay/sofa/boot/logging/initializer/DefaultLog4j2ReInitializer.java
  sofa-boot-project/sofa-boot-core/log-sofa-boot/src/main/java/com/alipay/sofa/boot/logging/initializer/DefaultLogbackReInitializer.java
  sofa-boot-project/sofa-boot-core/log-sofa-boot/src/main/java/com/alipay/sofa/boot/logging/log4j2/SOFAConfigurationFactory.java
  sofa-boot-project/sofa-boot-core/log-sofa-boot/src/main/java/com/alipay/sofa/boot/logging/util/SystemPropertiesGetter.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/context/ApplicationContextRefreshedListener.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/context/ApplicationEnvironmentPreparedListener.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/resources/com/alipay/sofa/rpc/boot/log/log4j2/log-conf.xml
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/log/RuntimeLoggerFactory.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/log/SofaLogger.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/resources/com/alipay/sofa/runtime/log/log4j2/log-conf.xml
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/resources/com/alipay/sofa/runtime/log/logback/log-conf.xml
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/src/main/java/com/alipay/sofa/tracer/boot/listener/SofaTracerConfigurationListener.java
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/src/main/resources/META-INF/services/com.alipay.sofa.common.log.spi.Log4j2FilterGenerator
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/src/main/resources/META-INF/services/com.alipay.sofa.common.log.spi.Log4j2ReInitializer
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/src/main/resources/META-INF/services/com.alipay.sofa.common.log.spi.LogbackFilterGenerator
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/src/main/resources/META-INF/services/com.alipay.sofa.common.log.spi.LogbackReInitializer
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/src/main/resources/META-INF/services/com.alipay.sofa.common.log.spi.ReInitializeChecker
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/src/main/resources/META-INF/spring.factories
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/src/test/java/com/alipay/sofa/common/boot/logging/test/BaseLogIntegrationTest.java
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/src/test/java/com/alipay/sofa/common/boot/logging/test/Log4j2IntegrationTest.java
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/src/test/java/com/alipay/sofa/common/boot/logging/test/LogbackIntegrationTest.java
  sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/test/log/AllInfraLoggerFactoryTest.java
  sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/test/log/base/BaseLogTest.java
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/XXL

#761 Refine sofa-common-tools external configuration
  sofa-boot-project/sofa-boot-core/log-sofa-boot/src/main/java/com/alipay/sofa/boot/logging/LogEnvironmentPreparingListener.java
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/src/test/java/com/alipay/sofa/common/boot/logging/test/BaseLogIntegrationTest.java
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/src/test/java/com/alipay/sofa/common/boot/logging/test/LogbackIntegrationTest.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/listener/SofaBootstrapRunListener.java
Labels: cla:yes, size/M

#762 Add jvm filter comments and logic refine
  sofa-boot-project/sofa-boot-core/log-sofa-boot/src/main/java/com/alipay/sofa/boot/logging/LogEnvironmentPreparingListener.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/filter/JvmFilterContext.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/filter/JvmFilterHolder.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/binding/JvmBindingAdapter.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/component/ReferenceComponent.java
  sofa-boot-project/sofa-boot-starters/runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/test/ambush/JvmFilterTest.java
  sofa-boot-project/sofa-boot-starters/runtime-sofa-boot-starter/src/test/java/com/alipay/sofa/runtime/test/ambush/JvmFilterTestConfiguration.java
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/M

#763 Add extension component fail insulator config, default to no
  sofa-boot-project/sofa-boot-autoconfigure/src/test/java/com/alipay/sofa/autoconfigure/test/runtime/SofaRuntimePropertiesTest.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/SofaRuntimeProperties.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/configure/SofaRuntimeConfigurationProperties.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/ext/component/ExtensionComponent.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/SofaEventHandlerTest.java
Labels: cla:yes, size/M

#764 Update to 3.4.6 to release
  pom.xml
  sofa-boot-project/pom.xml
  sofa-boot-project/sofa-boot-actuator-autoconfigure/pom.xml
  sofa-boot-project/sofa-boot-actuator/pom.xml
  sofa-boot-project/sofa-boot-autoconfigure/pom.xml
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/log-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/pom.xml
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/startup-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/test-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-parent/pom.xml
  sofa-boot-project/sofa-boot-plugins/pom.xml
  sofa-boot-project/sofa-boot-plugins/rpc-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-plugins/runtime-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-plugins/tracer-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-starters/healthcheck-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/infra-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/isle-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/pom.xml
  sofa-boot-project/sofa-boot-starters/rpc-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/runtime-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/startup-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/test-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/tracer-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-tools/pom.xml
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/build.gradle
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/pom.xml
  sofa-boot-project/sofa-boot/pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/M

#765 Update hessian to 3.3.12
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/XS
