Repository sofastack/sofa-boot, pull requests merged in 2020-03, with the labels that each got.

#602 3.3.1-SNAPSHOT
  pom.xml
  sofa-boot-project/pom.xml
  sofa-boot-project/sofa-boot-actuator-autoconfigure/pom.xml
  sofa-boot-project/sofa-boot-actuator/pom.xml
  sofa-boot-project/sofa-boot-autoconfigure/pom.xml
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/log-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/pom.xml
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/test-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-parent/pom.xml
  sofa-boot-project/sofa-boot-plugins/pom.xml
  sofa-boot-project/sofa-boot-plugins/rpc-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-plugins/runtime-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-plugins/tracer-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-starters/healthcheck-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/infra-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/isle-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/pom.xml
  sofa-boot-project/sofa-boot-starters/rpc-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/runtime-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/test-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/tracer-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-tools/pom.xml
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/build.gradle
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/pom.xml
  sofa-boot-project/sofa-boot/pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/M

#607 Fix MultiApplicationHealthIndicator stack overflow bug
  sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/health/MultiApplicationHealthIndicator.java
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/impl/SofaRuntimeHealthChecker.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/invoke/DynamicJvmServiceProxyFinder.java
Labels: cla:yes, size/S

#606 disable StandardSofaRuntimeManager auto shutdown
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/runtime/SofaRuntimeAutoConfiguration.java
Labels: cla:yes

#610 update spring boot version to 2.1.13.RELEASE
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/build.gradle
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/XS

#611 upgrade version 3.3.1
  pom.xml
  sofa-boot-project/pom.xml
  sofa-boot-project/sofa-boot-actuator-autoconfigure/pom.xml
  sofa-boot-project/sofa-boot-actuator/pom.xml
  sofa-boot-project/sofa-boot-autoconfigure/pom.xml
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/log-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/pom.xml
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/test-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-parent/pom.xml
  sofa-boot-project/sofa-boot-plugins/pom.xml
  sofa-boot-project/sofa-boot-plugins/rpc-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-plugins/runtime-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-plugins/tracer-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-starters/healthcheck-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/infra-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/isle-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/pom.xml
  sofa-boot-project/sofa-boot-starters/rpc-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/runtime-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/test-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/tracer-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-tools/pom.xml
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/build.gradle
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/pom.xml
  sofa-boot-project/sofa-boot/pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/M

#615 upgrade version 3.3.2-SNAPSHOT
  pom.xml
  sofa-boot-project/pom.xml
  sofa-boot-project/sofa-boot-actuator-autoconfigure/pom.xml
  sofa-boot-project/sofa-boot-actuator/pom.xml
  sofa-boot-project/sofa-boot-autoconfigure/pom.xml
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/log-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/pom.xml
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/test-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-parent/pom.xml
  sofa-boot-project/sofa-boot-plugins/pom.xml
  sofa-boot-project/sofa-boot-plugins/rpc-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-plugins/runtime-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-plugins/tracer-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-starters/healthcheck-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/infra-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/isle-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/pom.xml
  sofa-boot-project/sofa-boot-starters/rpc-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/runtime-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/test-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/tracer-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-tools/pom.xml
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/build.gradle
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/pom.xml
  sofa-boot-project/sofa-boot/pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/M

#587 Sort BindingAdapter and BindingConverter so that users can easily override them
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/adapter/BindingAdapterFactoryTest.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/adapter/XBindingAdapter.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/adapter/XBindingAdapter2.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/adapter/XBindingAdapter3.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/converter/RpcBindingConverterTest.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/converter/TestBindingConverter.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/converter/TestBindingConverter2.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/converter/TestBindingConverter3.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/resources/META-INF/services/com.alipay.sofa.runtime.spi.binding.BindingAdapter
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/resources/META-INF/services/com.alipay.sofa.runtime.spi.service.BindingConverter
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/impl/BindingAdapterFactoryImpl.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/impl/BindingConverterFactoryImpl.java
Labels: First-time contributor, cla:yes, question, size/L

#601 feat:health check for target url
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/binding/RpcBinding.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/param/RpcBindingParam.java
Labels: cla:yes, size/L

#584 Support bolt swagget
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/SofaRpcAutoConfiguration.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/config/SofaBootRpcProperties.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/swagger/BoltSwaggerServiceApplicationListener.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/swagger/SwaggerServiceImpl.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/SofaRpcTestAutoConfiguration.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/readiness/ReadinessTest.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/swagger/SwaggerTest.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/resources/spring/bolt_swagger.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: First-time contributor, cla:yes, size/L

#612 support mock setting
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/SofaRpcAutoConfiguration.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/config/SofaBootRpcProperties.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/container/ConsumerConfigContainer.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/adapter/RpcBindingAdapter.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/adapter/helper/ConsumerConfigHelper.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/adapter/processor/ConsumerConfigProcessor.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/adapter/processor/ConsumerMockProcessor.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/adapter/processor/DynamicConfigProcessor.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/adapter/processor/ProcessorContainer.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/adapter/processor/ProviderConfigProcessor.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/binding/RpcBindingXmlConstants.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/converter/RpcBindingConverter.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/param/RpcBindingParam.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/SofaRpcTestAutoConfiguration.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/mock/HttpMockServer.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/mock/MockBeanConfigTest.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/mock/xml/XmlConfigTest.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/runtime/adapter/processor/ConsumerMockProcessorTest.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/runtime/adapter/processor/DynamicConfigProcessorTest.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/runtime/adapter/processor/ProcessorAutoConfigTest.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/resources/spring/test_only_mock.xml
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/resources/spring/test_only_mock_bean.xml
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/api/annotation/SofaReferenceBinding.java
  sofa-boot-project/sofa-boot/src/main/resources/com/alipay/sofa/boot/spring/namespace/schema/rpc.xsd
Labels: First-time contributor, cla:yes, size/XL

#596 Feat/rpc error code
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/common/SofaBootRpcSpringUtil.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/container/RegistryConfigContainer.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/container/ServerConfigContainer.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/container/RegistryConfigContainerTest.java
Labels: cla:yes, size/M

#600 feat: rest auto registe
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/SofaRpcAutoConfiguration.java
Labels: cla:yes, size/M

#621 upgrade sofa ark version
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/XS

#619 modify SofaLogger implementation
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/loader/DynamicSpringContextLoader.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/spring/listener/SofaModuleContextRefreshedListener.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/stage/AbstractPipelineStage.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/stage/SpringContextInstallStage.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/component/impl/ComponentManagerImpl.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/ext/component/ExtensionComponent.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/ext/spring/ExtensionFactoryBean.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/ext/spring/ExtensionPointFactoryBean.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/log/SofaLogger.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/binding/JvmBindingAdapter.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/component/ReferenceComponent.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/component/ServiceComponent.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/ServiceBeanFactoryPostProcessor.java
  sofa-boot-project/sofa-boot-starters/tracer-sofa-boot-starter/src/test/java/com/alipay/sofa/tracer/boot/springmvc/SpringMvcFilterJsonOutputTest.java
Labels: cla:yes, size/L

#626 feat:triple
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/config/SofaBootRpcConfigConstants.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/config/SofaBootRpcProperties.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/container/ServerConfigContainer.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/adapter/TripleBindingAdapter.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/binding/RpcBindingType.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/binding/TripleBinding.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/converter/TripleBindingConverter.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/param/TripleBindingParam.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/SofaBootRpcAllTest.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/bean/triple/TripleGreeterImpl.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/resources/META-INF/services/com.alipay.sofa.runtime.spi.binding.BindingAdapter
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/resources/META-INF/services/com.alipay.sofa.runtime.spi.service.BindingConverter
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/resources/spring/test_all.xml
  sofa-boot-project/sofa-boot-starters/rpc-sofa-boot-starter/src/main/resources/META-INF/services/com.alipay.sofa.runtime.spi.binding.BindingAdapter
  sofa-boot-project/sofa-boot-starters/rpc-sofa-boot-starter/src/main/resources/META-INF/services/com.alipay.sofa.runtime.spi.service.BindingConverter
  sofa-boot-project/sofa-boot/src/main/resources/com/alipay/sofa/boot/spring/namespace/schema/rpc.xsd
Labels: cla:yes, size/L

#628 SofaModulePostProcessorShareManager detect null parameter
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/spring/share/SofaModulePostProcessorShareManager.java
Labels: cla:yes

#630 ReadinessCheckCallback when health check paas
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/ReadinessCheckListener.java
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/test/java/com/alipay/sofa/healthcheck/test/AfterHealthReadinessCheckCallbackTest.java
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/test/java/com/alipay/sofa/healthcheck/test/bean/FailedHealthCheck.java
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/test/java/com/alipay/sofa/healthcheck/test/bean/SuccessHealthCheck.java
Labels: cla:yes, question, size/L

#631 upgrade version to 3.3.2
  pom.xml
  sofa-boot-project/pom.xml
  sofa-boot-project/sofa-boot-actuator-autoconfigure/pom.xml
  sofa-boot-project/sofa-boot-actuator/pom.xml
  sofa-boot-project/sofa-boot-autoconfigure/pom.xml
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/log-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/pom.xml
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/test-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-parent/pom.xml
  sofa-boot-project/sofa-boot-plugins/pom.xml
  sofa-boot-project/sofa-boot-plugins/rpc-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-plugins/runtime-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-plugins/tracer-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-starters/healthcheck-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/infra-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/isle-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/pom.xml
  sofa-boot-project/sofa-boot-starters/rpc-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/runtime-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/test-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/tracer-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-tools/pom.xml
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/build.gradle
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/pom.xml
  sofa-boot-project/sofa-boot/pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/M
