Repository sofastack/sofa-boot, pull requests merged in 2020-10, with the labels that each got.

#516 change getBoolean to parseBoolean in ParserUtils
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spi/util/ParserUtils.java
Labels: cla:yes, size/XS

#734 allow-close-isle-health
  sofa-boot-project/sofa-boot-actuator-autoconfigure/src/main/java/com/alipay/sofa/boot/actuator/autoconfigure/health/SofaBootHealthCheckAutoConfiguration.java
Labels: cla:yes, size/XS

#733 upgrade junit version to 4.13.1
  sofa-boot-project/sofa-boot-parent/pom.xml
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/build.gradle
Labels: cla:yes, size/XS

#736 move LICENSE to project root
  LICENSE
Labels: cla:yes, size/XS

#738 upgrade-ark-to-1.1.5
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/XS

#739 prepare-release-3.4.5
  pom.xml
  sofa-boot-project/pom.xml
  sofa-boot-project/sofa-boot-actuator-autoconfigure/pom.xml
  sofa-boot-project/sofa-boot-actuator/pom.xml
  sofa-boot-project/sofa-boot-autoconfigure/pom.xml
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/log-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/pom.xml
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/startup-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/test-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-parent/pom.xml
  sofa-boot-project/sofa-boot-plugins/pom.xml
  sofa-boot-project/sofa-boot-plugins/rpc-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-plugins/runtime-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-plugins/tracer-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-starters/healthcheck-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/infra-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/isle-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/pom.xml
  sofa-boot-project/sofa-boot-starters/rpc-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/runtime-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/startup-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/test-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/tracer-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-tools/pom.xml
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/build.gradle
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/pom.xml
  sofa-boot-project/sofa-boot/pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/M

#731 BeanLoadCost hierarchical display
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/spring/factory/BeanLoadCostBeanFactory.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/stage/ModuleLogOutputStage.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/ApplicationRuntimeModelTest.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/BeanHierarchyTest.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/service/Child1.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/service/Child2.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/service/Child3.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/service/GrandChild1.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/service/GrandChild2.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/service/GrandChild3.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/service/IService.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/service/ServiceImpl.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/resources/module/META-INF/spring/beans.xml
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/resources/module/sofa-module.properties
Labels: cla:yes, size/XL

#740 Register module ApplicationContext as sofa components
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/ApplicationRuntimeModel.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/stage/ModelCreatingStage.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/stage/SpringContextInstallStage.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/FailModuleTest.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/FailModuleWithParallelTest.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/ModelCreatingStageTest.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/logging.path_IS_UNDEFINED/rpc/triple-threadpool.log
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/SpringContextComponent.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/SpringContextImplementation.java
  sofa-boot-project/sofa-boot-core/startup-sofa-boot/src/test/java/com/alipay/sofa/startup/test/IsleStageCostTest.java
  sofa-boot-project/sofa-boot-starters/isle-sofa-boot-starter/src/test/java/com/alipay/sofa/isle/IsleSpringComponentTest.java
  sofa-boot-project/sofa-boot-starters/isle-sofa-boot-starter/src/test/java/com/alipay/sofa/isle/TestModelCreatingStage.java
  sofa-boot-project/sofa-boot-starters/isle-sofa-boot-starter/src/test/resources/module1/META-INF/spring/beans.xml
  sofa-boot-project/sofa-boot-starters/isle-sofa-boot-starter/src/test/resources/module1/sofa-module.properties
  sofa-boot-project/sofa-boot-starters/isle-sofa-boot-starter/src/test/resources/module2/META-INF/spring/beans.xml
  sofa-boot-project/sofa-boot-starters/isle-sofa-boot-starter/src/test/resources/module2/sofa-module.properties
Labels: cla:yes, size/L

#745 clean sofa-boot-samples module
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/PostProcessorShareTest.java
Labels: cla:yes, size/S

#742 bugfix: tracer miss context
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/src/main/java/com/alipay/sofa/tracer/boot/flexible/processor/SofaTracerMethodInvocationProcessor.java
Labels: First-time contributor, cla:yes, size/XS

#747 Update sofa hessian to 3.3.10
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/XS

#670 Add @Override annotation to NewThread of NamedThreadFactory
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/util/NamedThreadFactory.java
Labels: First-time contributor, cla:yes, size/XS

#748 Make PMD rules apply for tests and code refactor
  sofa-boot-project/sofa-boot-actuator/src/test/java/com/alipay/sofa/boot/actuator/test/SofaBootHealthIndicatorTest.java
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/test/java/com/alipay/sofa/healthcheck/test/HealthCheckInsulatorTest.java
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/test/java/com/alipay/sofa/healthcheck/test/HealthCheckerProcessorTest.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/FailModuleTest.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/PostProcessorShareTest.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/common/ThreadPoolMonitorTest.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/converter/RpcBindingConverterTest.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/extension/bean/IExtensionImpl.java
  sofa-boot-project/sofa-boot-parent/pom.xml
  sofa-boot-project/sofa-boot-starters/isle-sofa-boot-starter/src/test/java/com/alipay/sofa/isle/TestModelCreatingStage.java
  sofa-boot-project/sofa-boot-starters/tracer-sofa-boot-starter/src/test/java/com/alipay/sofa/tracer/boot/base/SpringBootWebApplication.java
  sofa-boot-project/sofa-boot-starters/tracer-sofa-boot-starter/src/test/java/com/alipay/sofa/tracer/boot/springmvc/SpringMvcFilterJsonOutputTest.java
  sofa-boot-project/sofa-boot-starters/tracer-sofa-boot-starter/src/test/java/com/alipay/sofa/tracer/boot/springmvc/WebFluxTracerTest.java
Labels: cla:yes, size/M
