Repository sofastack/sofa-boot, pull requests merged in 2020-08, with the labels that each got.

#683 resolve dependabot alerts
  sofa-boot-project/sofa-boot-autoconfigure/pom.xml
  sofa-boot-project/sofa-boot-parent/pom.xml
Labels: cla:yes, size/M

#686 Update version to 3.4.3 for GA
  pom.xml
  sofa-boot-project/pom.xml
  sofa-boot-project/sofa-boot-actuator-autoconfigure/pom.xml
  sofa-boot-project/sofa-boot-actuator/pom.xml
  sofa-boot-project/sofa-boot-autoconfigure/pom.xml
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/log-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/pom.xml
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/startup-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/test-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-parent/pom.xml
  sofa-boot-project/sofa-boot-plugins/pom.xml
  sofa-boot-project/sofa-boot-plugins/rpc-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-plugins/runtime-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-plugins/tracer-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-starters/healthcheck-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/infra-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/isle-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/pom.xml
  sofa-boot-project/sofa-boot-starters/rpc-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/runtime-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/startup-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/test-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/tracer-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-tools/pom.xml
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/build.gradle
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/pom.xml
  sofa-boot-project/sofa-boot/pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/M, upgrade

#687 Fix service/reference component health problem
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/component/ReferenceComponent.java
Labels: bug, cla:yes, size/XS

#693 Upgrade version 3.4.4 snapshot
  pom.xml
  sofa-boot-project/pom.xml
  sofa-boot-project/sofa-boot-actuator-autoconfigure/pom.xml
  sofa-boot-project/sofa-boot-actuator/pom.xml
  sofa-boot-project/sofa-boot-autoconfigure/pom.xml
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/log-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/pom.xml
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/startup-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/test-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-parent/pom.xml
  sofa-boot-project/sofa-boot-plugins/pom.xml
  sofa-boot-project/sofa-boot-plugins/rpc-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-plugins/runtime-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-plugins/tracer-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-starters/healthcheck-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/infra-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/isle-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/pom.xml
  sofa-boot-project/sofa-boot-starters/rpc-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/runtime-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/startup-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/test-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/tracer-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-tools/pom.xml
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/build.gradle
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/pom.xml
  sofa-boot-project/sofa-boot/pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/M

#692 Fix log debug
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/invoke/DynamicJvmServiceProxyFinder.java
Labels: bug, cla:yes, size/S

#698 upgrade-ark-to-1.4.4
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/XS

#697 Fix extension healthcheck bug
  sofa-boot-project/sofa-boot-autoconfigure/src/test/java/com/alipay/sofa/autoconfigure/test/runtime/SofaRuntimePropertiesTest.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/SofaRuntimeProperties.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/configure/SofaRuntimeConfigurationProperties.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/ext/component/ExtensionComponent.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/SofaEventHandlerTest.java
Labels: bug, cla:yes, size/M

#696 fix log4j2 conf under throwable
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/resources/com/alipay/sofa/runtime/log/log4j2/log-conf.xml
  sofa-boot-project/sofa-boot/src/main/resources/com/alipay/sofa/infra/log/log4j2/log-conf.xml
Labels: bug, cla:yes, size/XS
