Repository sofastack/sofa-boot, pull requests merged in 2021-12, with the labels that each got.

#892 Update version to 3.10.0 snapshot
  pom.xml
Labels: cla:yes, size/XS

#894 Update SpringBoot version 2.3.12
  pom.xml
Labels: cla:yes, size/XS

#888 Throw exception when found duplicate module
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/ApplicationRuntimeModel.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/spring/config/SofaModuleProperties.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/stage/ModelCreatingStage.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/DuplicateModuleTest.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/resources/dup-module-0.1.0.jar
  sofa-boot-project/sofa-boot/src/main/resources/sofa-boot/log-codes.properties
Labels: question, cla:yes, size/L

#895 Fix some typos in code and comments
  CONTRIBUTING.md
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/ReadinessCheckListener.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/deployment/DependencyTree.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/deployment/impl/FileDeploymentDescriptor.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/profile/SofaModuleProfileChecker.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/spring/SofaModuleContextLifecycle.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/common/NetworkAddressUtil.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/adapter/BindingAdapterFactoryTest.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/bean/direct/DirectService.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/bean/direct/DirectServiceImpl.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/config/SofaRpcLoggerLevelConfigTest.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/common/xmap/XAnnotatedList.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/common/xmap/annotation/XNodeList.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/common/xmap/annotation/spring/XAnnotatedSpring.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/common/xmap/annotation/spring/XMapSpringUtil.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/api/annotation/SofaService.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/api/client/param/ExtensionParam.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/ClientFactoryTest.java
Labels: bug, size/M, cla:no, First-time contributor

#902 throw exception when some module install failed
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/spring/config/SofaModuleProperties.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/stage/SpringContextInstallStage.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/SpringContextInstallStageTest.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/resources/config/application.properties
  sofa-boot-project/sofa-boot/src/main/resources/sofa-boot/log-codes.properties
Labels: question, cla:yes, size/L

#903 add ignore param in log
  sofa-boot-project/sofa-boot/src/main/resources/sofa-boot/log-codes.properties
Labels: cla:yes, size/XS

#904 Release/3.10.0
  pom.xml
Labels: cla:yes, size/XS
