Repository sofastack/sofa-boot, pull requests merged in 2021-05, with the labels that each got.

#827 Use revision instead of hard-code version
  .gitignore
  pom.xml
  sofa-boot-project/pom.xml
  sofa-boot-project/sofa-boot-actuator-autoconfigure/pom.xml
  sofa-boot-project/sofa-boot-actuator/pom.xml
  sofa-boot-project/sofa-boot-autoconfigure/pom.xml
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/log-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/pom.xml
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/startup-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/test-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-parent/pom.xml
  sofa-boot-project/sofa-boot-plugins/pom.xml
  sofa-boot-project/sofa-boot-plugins/rpc-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-plugins/runtime-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-plugins/tracer-sofa-boot-plugin/pom.xml
  sofa-boot-project/sofa-boot-starters/healthcheck-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/isle-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/pom.xml
  sofa-boot-project/sofa-boot-starters/rpc-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/runtime-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/startup-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/test-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/tracer-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-tools/pom.xml
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/build.gradle
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/pom.xml
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/src/main/java/org/springframework/boot/gradle/plugin/SofaBootPlugin.java
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/src/test/java/org/springframework/boot/gradle/testkit/GradleBuild.java
  sofa-boot-project/sofa-boot/pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/L

#830 Fix tracer bean name conflicting with spring cloud
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/tracer/SofaTracerAutoConfiguration.java
Labels: bug, cla:yes, size/XS

#832 update sofa-common-tools 1.3.4
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/XS

#833 Update version to 3.7.0
  pom.xml
  tools/change_version.sh
Labels: cla:yes, size/M

#834 Fix grpc version problem
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: bug, cla:yes, size/XS
