Repository sofastack/sofa-boot, pull requests merged in 2021-04, with the labels that each got.

#812 add config to statics sofa bean
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/startup/SofaStartupAutoConfiguration.java
  sofa-boot-project/sofa-boot-core/startup-sofa-boot/src/main/java/com/alipay/sofa/startup/StartupProperties.java
  sofa-boot-project/sofa-boot-core/startup-sofa-boot/src/main/java/com/alipay/sofa/startup/stage/BeanCostBeanPostProcessor.java
  sofa-boot-project/sofa-boot-core/startup-sofa-boot/src/test/java/com/alipay/sofa/startup/test/configuration/SofaStartupAutoConfiguration.java
Labels: cla:yes, size/S

#810 Update sofa-common-tools to 1.3.3
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/XS

#813 Add issue banner
  README.md
Labels: cla:yes, size/XS

#814 fix properties overridden in ark environment
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/SofaRuntimeProperties.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/configure/SofaRuntimeConfigurationProperties.java
Labels: bug, cla:yes, size/M

#815 Provide English version REAME
  .github/workflows/maven.yml
  README.md
  README_ZH.md
Labels: cla:yes, size/L

#817 seperate ark/spring shutdown
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/runtime/SofaRuntimeAutoConfiguration.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/SofaBizUninstallEventHandler.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/component/impl/ComponentManagerImpl.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/component/impl/StandardSofaRuntimeManager.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spi/component/SofaRuntimeManager.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/SpringContextComponent.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/aware/DefaultRuntimeShutdownAware.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/SofaEventHandlerTest.java
Labels: cla:yes, size/L

#822 English version of readme and some refinements
  README.md
  README_ZH.md
Labels: cla:yes, size/M

#821 Change name of Github workflows
  .github/workflows/maven.yml
Labels: cla:yes, size/XS

#824 fix autoconfigruation in isle
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/startup/SofaStartupIsleAutoConfiguration.java
Labels: bug, cla:yes, size/XS
