Repository sofastack/sofa-boot, pull requests merged in 2022-08, with the labels that each got.

#1005 Update 315 snapshot
  pom.xml
Labels: cla:yes, size/XS

#984 Add source analyze doc(#954)
  README_ZH.md
Labels: cla:yes, size/XS

#1004 normalize copyright template
  LICENSE
Labels: cla:yes, size/XS

#1008 add a minor changes to log the missing modules in SpringContextInstallStage
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/stage/SpringContextInstallStage.java
Labels: cla:yes, size/S, First-time contributor

#1009 Update springboot 273
  pom.xml
Labels: cla:yes, size/XS

#1010 Add github action for release jar
  .github/workflows/release.yml
  pom.xml
Labels: size/M, cla:yes

#1011 update_3.14.1 and fix refrencefactory getObjectType
  pom.xml
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/factory/ReferenceFactoryBean.java
Labels: bug, cla:yes, size/S
