Repository sofastack/sofa-boot, pull requests merged in 2022-10, with the labels that each got.

#1017 3.16.0 xunfang
  pom.xml
Labels: cla:yes, size/XS

#1018 change var springPowered to deploymentMap
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/ApplicationRuntimeModel.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/loader/DynamicSpringContextLoader.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/stage/SpringContextInstallStage.java
Labels: cla:yes, size/S

#1025 restore getSpringPoweredDeployment()
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/ApplicationRuntimeModel.java
Labels: cla:yes, size/XS

#1030 sofa service name can append bean id if the com.alipay.sofa.boot.serv…
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/SofaRuntimeProperties.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/configure/SofaRuntimeConfigurationProperties.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/ServiceBeanFactoryPostProcessor.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/bean/SofaBeanNameGenerator.java
Labels: question, size/M, cla:yes, First-time contributor

#1031 Redirect sofa runtime log to console in test env
  sofa-boot-project/sofa-boot-core/log-sofa-boot/src/main/java/com/alipay/sofa/boot/logging/LocalEnvUtil.java
  sofa-boot-project/sofa-boot-core/log-sofa-boot/src/main/java/com/alipay/sofa/boot/logging/LogEnvironmentPreparingListener.java
Labels: cla:yes, size/S

#1032 enable com.alipay.sofa.proxy.bean default
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/runtime/SofaRuntimeAutoConfiguration.java
Labels: cla:yes, size/XS
