Repository sofastack/sofa-boot, pull requests merged in 2022-12, with the labels that each got.

#1041 Update jdk17
  .github/workflows/maven.yml
  .github/workflows/release.yml
  pom.xml
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/common/xmap/DOMSerializer.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/common/xmap/XAnnotatedContent.java
  sofa-boot-project/sofa-boot-parent/pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/L

#875 Add tracer autoconfigure. (#847)
  sofa-boot-project/sofa-boot-autoconfigure/pom.xml
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/tracer/SofaTracerKafkaAutoConfiguration.java
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/tracer/SofaTracerMongoAutoConfiguration.java
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/tracer/SofaTracerRabbitMqAutoConfiguration.java
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/tracer/SofaTracerRedisAutoConfiguration.java
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/tracer/SofaTracerRocketMqAutoConfiguration.java
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/tracer/SpringMessageAutoConfiguration.java
  sofa-boot-project/sofa-boot-autoconfigure/src/main/resources/META-INF/spring.factories
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/src/main/java/com/alipay/sofa/tracer/boot/kafka/processor/KafkaConsumerFactoryPostProcessor.java
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/src/main/java/com/alipay/sofa/tracer/boot/kafka/processor/KafkaProducerFactoryPostProcessor.java
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/src/main/java/com/alipay/sofa/tracer/boot/message/processor/StreamRocketMQTracerBeanPostProcessor.java
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/src/main/java/com/alipay/sofa/tracer/boot/mongodb/SofaTracerMongoClientSettingsBuilderCustomizer.java
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/src/main/java/com/alipay/sofa/tracer/boot/rabbitmq/processor/SofaTracerRabbitMqBeanPostProcessor.java
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/src/main/java/com/alipay/sofa/tracer/boot/rocketmq/processor/SofaTracerRocketMqConsumerPostProcessor.java
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/src/main/java/com/alipay/sofa/tracer/boot/rocketmq/processor/SofaTracerRocketMqProducerPostProcessor.java
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/src/test/com/alipay/sofa/tracer/boot/mongodb/SofaTracerMongoClientSettingsBuilderCustomizerTest.java
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/src/test/com/alipay/sofa/tracer/boot/rocketmq/processor/SofaTracerRocketMqConsumerPostProcessorTest.java
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/src/test/com/alipay/sofa/tracer/boot/rocketmq/processor/SofaTracerRocketMqProducerPostProcessorTest.java
  sofa-boot-project/sofa-boot-parent/pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/XXL

#1046 fix HealthIndicatorProcessor.doHealthCheck() bug when exception occur
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/HealthIndicatorProcessor.java
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/test/java/com/alipay/sofa/healthcheck/test/HealthIndicatorCheckProcessorTest.java
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/test/java/com/alipay/sofa/healthcheck/test/bean/TimeoutHealthIndicator.java
Labels: bug, question, size/M, cla:yes

#1048 Change version to 3.16.2
  pom.xml
Labels: cla:yes, size/XS
