Repository sofastack/sofa-boot, pull requests merged in 2022-06, with the labels that each got.

#976 Ignore component success detail
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/impl/ComponentHealthChecker.java
Labels: cla:yes, size/S

#977 Update healthcheck info
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/HealthCheckerProcessor.java
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/impl/ModuleHealthChecker.java
Labels: cla:yes, size/S

#979 Fix on application event
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/context/ApplicationContextClosedListener.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/context/ApplicationContextRefreshedListener.java
Labels: bug, size/M, cla:yes

#980 Release 3.13.0
  pom.xml
Labels: cla:yes, size/XS

#986 Update Springboot 2.6.8
  pom.xml
  sofa-boot-project/sofa-boot-core/startup-sofa-boot/src/main/java/com/alipay/sofa/startup/stage/StartupSpringApplicationRunListener.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/env/EnvironmentCustomizer.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/startup/BootStageConstants.java
Labels: size/M, cla:yes

#987 Update 3.14.0
  pom.xml
Labels: cla:yes, size/XS

#991 update springboot 2.6.9
  pom.xml
Labels: cla:yes, size/XS

#992 优化 DynamicSpringContextLoader 的逻辑，并把相关 BeanFactory 和上下文放到 sofa-runtime 中
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/loader/DynamicSpringContextLoader.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/stage/ModuleLogOutputStage.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/AsyncInitBeanDefinitionDecoratorTest.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/BeanHierarchyTest.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/context/SofaApplicationContext.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/factory/BeanLoadCostBeanFactory.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/util/SofaSpringContextUtil.java
  sofa-boot-project/sofa-boot-core/startup-sofa-boot/src/main/java/com/alipay/sofa/startup/stage/isle/StartupSpringContextInstallStage.java
Labels: cla:yes, size/L

#993 update SofaSpringContextUtil
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/util/SofaSpringContextUtil.java
Labels: cla:yes, size/XS

#994 Update dynamic spring context loader method
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/loader/DynamicSpringContextLoader.java
Labels: cla:yes, size/S
