Repository sofastack/sofa-boot, pull requests merged in 2022-07, with the labels that each got.

#989 Set slf4j version
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/XS

#995 move SofaModuleBeanFactoryPostProcessor to sofa-runtime
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/isle/SofaModuleAutoConfiguration.java
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/runtime/SofaRuntimeAutoConfiguration.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/FailModuleTest.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/PostProcessorShareTest.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/SofaShareBeanFactoryPostProcessor.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/share/SofaPostProcessorShareFilter.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/share/SofaPostProcessorShareManager.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/share/UnshareSofaPostProcessor.java
  sofa-boot-project/sofa-boot-core/startup-sofa-boot/src/main/java/com/alipay/sofa/startup/stage/BeanCostBeanPostProcessor.java
  sofa-boot-project/sofa-boot-core/startup-sofa-boot/src/test/java/com/alipay/sofa/startup/test/configuration/SofaStartupIsleAutoConfiguration.java
Labels: cla:yes, size/L

#990 Module self depend on detection
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/deployment/DependencyTree.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/DependencyTreeTest.java
  sofa-boot-project/sofa-boot/src/main/resources/sofa-boot/log-codes.properties
Labels: size/M, cla:yes

#997 support custom HealthCheckerComparator
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/core/HealthCheckerComparatorProvider.java
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/util/HealthCheckUtils.java
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/test/java/com/alipay/sofa/healthcheck/test/HealthCheckUtilsTest.java
Labels: cla:yes, size/L

#982 fix typo
  README.md
Labels: bug, cla:yes, size/XS

#999 fix moving BeanLoadCostBeanFactory
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/AsyncInitBeanDefinitionDecoratorTest.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/AsyncInitBeanFactoryPostProcessor.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/AsyncProxyBeanPostProcessor.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/parser/AsyncInitBeanDefinitionDecorator.java
Labels: bug, size/M, cla:yes

#1002 adjust priority for AfterBizStartupEventHandler
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/AfterBizStartupEventHandler.java
Labels: cla:yes, size/XS, First-time contributor

#1001 Support module application api
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/ApplicationRuntimeModel.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/IsleDeploymentModel.java
Labels: size/M, cla:yes

#1003 Release 3.14.0
  pom.xml
Labels: cla:yes, size/XS
