Repository sofastack/sofa-boot, pull requests merged in 2023-05, with the labels that each got.

#1174 update_3.19.0-SNAPSHOT
  pom.xml
  sofa-boot-project/sofa-boot-core/startup-sofa-boot/src/test/java/com/alipay/sofa/startup/test/IsleCheckStartupReporterTest.java
Labels: cla:yes

#1177 Avoid NPE when unregister
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/component/impl/ComponentManagerImpl.java
Labels: question, cla:yes, size/XS

#1176 Add annotation sofa service bean
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/api/annotation/SofaServiceBean.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/ServiceBeanTest.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/beans/service/SofaServiceBeanService.java
Labels: cla:yes, size/L

#1178 fix toolkit-common-logging config bug
  sofa-boot-project/sofa-boot-core/log-sofa-boot/src/main/java/com/alipay/sofa/boot/logging/LogEnvironmentPreparingListener.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/listener/SofaConfigSourceSupportListener.java
Labels: bug, cla:yes, size/XS
