Repository sofastack/sofa-boot, pull requests merged in 2023-06, with the labels that each got.

#1179 straight application listener order
  sofa-boot-project/sofa-boot-core/log-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/log-sofa-boot/src/main/java/com/alipay/sofa/boot/logging/LogEnvironmentPreparingListener.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/src/main/java/com/alipay/sofa/tracer/boot/listener/SofaTracerConfigurationListener.java
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/src/test/java/com/alipay/sofa/common/boot/logging/test/GlobalConsoleLevelConfigTest.java
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/src/test/java/com/alipay/sofa/common/boot/logging/test/GlobalSpaceOverrideConfigTest.java
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/src/test/java/com/alipay/sofa/common/boot/logging/test/GlobalSpaceOverrideTest.java
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/src/test/java/com/alipay/sofa/common/boot/logging/test/GlobbingLogLevelTest.java
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/src/test/java/com/alipay/sofa/common/boot/logging/test/Log4j2ThreadContextTest.java
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/src/test/java/com/alipay/sofa/common/boot/logging/test/LogTestBase.java
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/src/test/java/com/alipay/sofa/common/boot/logging/test/LogbackConsoleLoggingTest.java
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/src/test/java/com/alipay/sofa/common/boot/logging/test/SpaceConsoleConfigTest.java
  sofa-boot-project/sofa-boot/pom.xml
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/listener/SofaBootstrapRunListener.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/listener/SofaConfigSourceSupportListener.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/util/ApplicationListenerOrderConstants.java
  sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/test/cloud/SpringCloudEnvTest.java
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/L

#1181 Avoid npe in BeanLoadCostBeanFactory#outputBeanStats
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/factory/BeanLoadCostBeanFactory.java
Labels: cla:yes, size/XS

#1182 Merge v3.19.0
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/tracer/SofaTracerConfigurationListener.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/api/annotation/SofaServiceBean.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/impl/ComponentManagerImpl.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/listener/SofaConfigSourceSupportListener.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/listener/SpringCloudConfigListener.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/logging/LogEnvironmentPostProcessor.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/util/ApplicationListenerOrderConstants.java
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-runtime/src/main/java/com/alipay/sofa/smoke/tests/runtime/impl/SofaServiceBeanService.java
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-runtime/src/test/java/com/alipay/sofa/smoke/tests/runtime/spring/SofaServiceBeanAnnotationTests.java
Labels: cla:yes, size/L

#1183 update springboot 3.0.7
  pom.xml
Labels: cla:yes, size/XS

#1184 update listener order
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/tracer/SofaTracerConfigurationListener.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/constant/ApplicationListenerOrderConstants.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/listener/SofaConfigSourceSupportListener.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/listener/SpringCloudConfigListener.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/logging/LogEnvironmentPostProcessor.java
Labels: size/M, cla:yes

#1185 1. distinct requrie modules
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/boot/isle/ApplicationRuntimeModel.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/boot/isle/deployment/AbstractDeploymentDescriptor.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/boot/isle/deployment/DefaultModuleDeploymentValidator.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/boot/isle/stage/ModelCreatingStage.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/boot/isle/ApplicationRuntimeModelTests.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/boot/isle/deployment/DefaultModuleDeploymentValidatorTests.java
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-isle/src/main/resources/nospring-module/sofa-module.properties
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-isle/src/main/resources/nospringchild-module/META-INF/spring/service.xml
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-isle/src/main/resources/nospringchild-module/sofa-module.properties
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-isle/src/test/java/com/alipay/sofa/smoke/tests/isle/DefaultSofaModuleProfileCheckerIntegrationTests.java
Labels: size/M, cla:yes

#1186 Revert extenstion package
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/ext/client/ExtensionClientImpl.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/ext/component/ExtensionComponent.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/ext/component/ExtensionInternal.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/ext/component/ExtensionPointComponent.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/ext/component/ExtensionPointInternal.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/ext/spring/ExtensionBuilder.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/ext/spring/ExtensionPointBuilder.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/service/api/component/Extensible.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/service/api/component/Extension.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/service/api/component/ExtensionPoint.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/ext/component/ExtensionComponentTests.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/ext/component/ExtensionPointComponentTests.java
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-actuator/src/main/java/com/alipay/sofa/smoke/tests/actuator/sample/beans/ExtensionBean.java
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-runtime/src/main/java/com/alipay/sofa/smoke/tests/runtime/extension/bean/IExtensionImpl.java
Labels: size/M, cla:yes

#1187 release 3.19.0
  pom.xml
Labels: cla:yes, size/XS

#1189 Add legacy rpc property
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/SofaBootRpcProperties.java
Labels: cla:yes, size/S

#1190 Release dependencies
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/S

#1192 1. update version 3.18.1
  pom.xml
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/ServiceBeanFactoryPostProcessor.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/RepeatableSofaServiceTest.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/util/SmartAnnotationUtils.java
  sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/test/util/SmartAnnotationUtilsTest.java
Labels: cla:yes, size/L

#1193 fix_SofaTracerConfigurationListener_order
  pom.xml
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/util/ApplicationListenerOrderConstants.java
Labels: bug, cla:yes, size/XS

#1194 fix @SofaService Annotation parse
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/ServiceBeanFactoryPostProcessor.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/RepeatableSofaServiceTest.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/util/SmartAnnotationUtils.java
  sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/test/util/SmartAnnotationUtilsTest.java
Labels: bug, cla:yes, size/L

#1195 Cherry pick 3.21.1
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/ServiceBeanFactoryPostProcessor.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/util/SmartAnnotationUtils.java
  sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/util/SmartAnnotationUtilsTests.java
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-runtime/src/test/java/com/alipay/sofa/smoke/tests/runtime/spring/RepeatableSofaServiceTests.java
Labels: cla:yes, size/L

#1197 release_3.19.1
  pom.xml
Labels: cla:yes, size/XS

#1198 Release 4.0.0
  pom.xml
Labels: cla:yes, size/XS
