Repository sofastack/sofa-boot, pull requests merged in 2023-03, with the labels that each got.

#1102 Update maven dependncies
  pom.xml
  sofa-boot-project/sofa-boot-core/ark-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-parent/pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
  sofa-boot-tests/pom.xml
Labels: size/M, cla:yes

#1103 Release 3.17.0
  pom.xml
Labels: cla:yes, size/XS

#1104 Add sofaboot swtich
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/condition/OnSwitchCondition.java
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/ConsulRegistryConfiguration.java
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/LocalRegistryConfiguration.java
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/MeshRegistryConfiguration.java
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/MulticastRegistryConfiguration.java
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/NacosRegistryConfiguration.java
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/RestFilterConfiguration.java
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/SofaRegistryConfiguration.java
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/SofaRpcAutoConfiguration.java
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/SwaggerConfiguration.java
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/ZookeeperRegistryConfiguration.java
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/runtime/SofaRuntimeAutoConfiguration.java
  sofa-boot-project/sofa-boot-autoconfigure/src/test/java/com/alipay/sofa/boot/autoconfigure/rpc/SofaRpcAutoConfigurationTests.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/context/SofaBootRpcStartListener.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/Initializer/SwitchableApplicationContextInitializer.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/listener/SwitchableApplicationListener.java
  sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/initializer/SampleSwitchSpringContextInitializerTests.java
  sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/lisener/SwitchableApplicationListenerTests.java
Labels: cla:yes, size/L

#1105 remove health indicator
  sofa-boot-project/sofa-boot-actuator-autoconfigure/src/main/java/com/alipay/sofa/boot/actuator/autoconfigure/health/ReadinessAutoConfiguration.java
  sofa-boot-project/sofa-boot-actuator-autoconfigure/src/test/java/com/alipay/sofa/boot/actuator/autoconfigure/health/ReadinessAutoConfigurationTests.java
  sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/health/HealthCheckerProcessor.java
  sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/health/HealthIndicatorProcessor.java
  sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/health/SofaBootHealthIndicator.java
  sofa-boot-project/sofa-boot-actuator/src/test/java/com/alipay/sofa/boot/actuator/health/HealthCheckerProcessorTests.java
  sofa-boot-project/sofa-boot-actuator/src/test/java/com/alipay/sofa/boot/actuator/health/SofaBootHealthIndicatorTests.java
Labels: cla:yes, size/L

#1108 support healthcheck startup
  sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/health/HealthCheckerProcessor.java
  sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/health/HealthIndicatorProcessor.java
  sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/health/ReadinessCheckCallbackProcessor.java
  sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/health/ReadinessCheckListener.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/startup/BaseStat.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/startup/BeanStat.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/startup/StartupSpringApplicationRunListener.java
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-actuator/src/test/java/com/alipay/sofa/smoke/tests/actuator/startup/HealthStageStartupReporterTests.java
Labels: cla:yes, size/L

#1109 Update tracer 4.0.0
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/tracer/SofaTracerConfigurationListener.java
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/tracer/feign/FeignClientAutoConfiguration.java
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/tracer/springmvc/OpenTracingSpringMvcAutoConfiguration.java
  sofa-boot-project/sofa-boot-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  sofa-boot-project/sofa-boot-autoconfigure/src/test/java/com/alipay/sofa/boot/autoconfigure/tracer/SofaTracerConfigurationListenerTests.java
  sofa-boot-project/sofa-boot-autoconfigure/src/test/java/com/alipay/sofa/boot/autoconfigure/tracer/springmvc/OpenTracingSpringMvcAutoConfigurationTests.java
  sofa-boot-project/sofa-boot-autoconfigure/src/test/resources/config/application.properties
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/src/main/java/com/alipay/sofa/boot/tracer/datasource/DataSourceBeanPostProcessor.java
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/src/main/java/com/alipay/sofa/boot/tracer/feign/FeignContextBeanPostProcessor.java
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/src/main/resources/META-INF/spring.factories
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/src/test/java/com/alipay/sofa/boot/tracer/datasource/DataSourceBeanPostProcessorTests.java
  sofa-boot-project/sofa-boot-core/tracer-sofa-boot/src/test/java/com/alipay/sofa/boot/tracer/feign/FeignContextBeanPostProcessorTests.java
  sofa-boot-project/sofaboot-dependencies/pom.xml
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-tracer/pom.xml
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-tracer/src/main/java/com/alipay/sofa/smoke/tests/tracer/sample/DataSourceConfiguration.java
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-tracer/src/main/java/com/alipay/sofa/smoke/tests/tracer/sample/RestTemplateConfiguration.java
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-tracer/src/main/java/com/alipay/sofa/smoke/tests/tracer/sample/TracerController.java
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-tracer/src/test/java/com/alipay/sofa/smoke/tests/tracer/TracerDataSourceTests.java
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-tracer/src/test/java/com/alipay/sofa/smoke/tests/tracer/TracerMvcTests.java
Labels: cla:yes, size/XXL

#1106 reactor switch on scenes
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/env/ScenesEnvironmentPostProcessor.java
  sofa-boot-project/sofa-boot/src/main/resources/META-INF/spring.factories
  sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/env/ScenesEnvironmentPostProcessorTests.java
  sofa-boot-project/sofa-boot/src/test/resources/sofa-boot/scenes/function.properties
  sofa-boot-project/sofa-boot/src/test/resources/sofa-boot/scenes/function.yml
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-boot/src/main/resources/config/application-dev.properties
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-boot/src/main/resources/config/application-function.properties
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-boot/src/main/resources/sofa-boot/scenes/function.properties
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-boot/src/main/resources/sofa-boot/scenes/function.yml
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-boot/src/test/java/com/alipay/sofa/smoke/tests/boot/SofaConditionOnSwitchTests.java
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/main/resources/application.yml
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/main/resources/sofa-boot/scenes/function-test.properties
Labels: cla:yes, size/L

#1111 Fix components end point (#1078)
  sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/components/ComponentsEndPoint.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/startup/StartupReporter.java
Labels: bug, cla:yes, size/XS

#1112 add scenes log
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/constant/SofaBootConstants.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/env/ScenesEnvironmentPostProcessor.java
Labels: cla:yes, size/S

#1113 1. update springboot 3.0.4
  pom.xml
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/boot/isle/loader/DynamicSpringContextLoader.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/context/SofaGenericApplicationContext.java
  sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/context/SofaGenericApplicationContextTests.java
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: size/M, cla:yes

#1114 support custom readiness actuator http response code
  sofa-boot-project/sofa-boot-actuator-autoconfigure/src/main/java/com/alipay/sofa/boot/actuator/autoconfigure/health/HealthProperties.java
  sofa-boot-project/sofa-boot-actuator-autoconfigure/src/main/java/com/alipay/sofa/boot/actuator/autoconfigure/health/ReadinessEndpointAutoConfiguration.java
  sofa-boot-project/sofa-boot-actuator-autoconfigure/src/main/java/com/alipay/sofa/boot/actuator/autoconfigure/health/SofaHttpCodeStatusMapper.java
  sofa-boot-project/sofa-boot-actuator-autoconfigure/src/test/java/com/alipay/sofa/boot/actuator/autoconfigure/health/ReadinessEndpointAutoConfigurationTests.java
  sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/health/ReadinessHttpCodeStatusMapper.java
  sofa-boot-project/sofa-boot-actuator/src/test/java/com/alipay/sofa/boot/actuator/health/ReadinessHttpCodeStatusMapperTests.java
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-actuator/src/test/java/com/alipay/sofa/smoke/tests/actuator/health/ReadienssHttpCodeStatusMapperTests.java
Labels: cla:yes, size/L

#1115 Support startup parent self time
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/startup/BeanStat.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/startup/StartupReporter.java
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-actuator/src/test/java/com/alipay/sofa/smoke/tests/actuator/startup/DefaultStageStartupReporterTests.java
Labels: size/M, cla:yes

#1118 update swagger and swagger2 version
  sofa-boot-project/sofa-boot-autoconfigure/pom.xml
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/SwaggerConfiguration.java
  sofa-boot-project/sofa-boot-autoconfigure/src/test/java/com/alipay/sofa/boot/autoconfigure/rpc/SofaRpcAutoConfigurationTests.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/pom.xml
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/test/java/com/alipay/sofa/smoke/tests/rpc/boot/SofaBootRpcApplicationTests.java
Labels: cla:yes, size/L

#1116 Feature same module inject
  pom.xml
  sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/components/SofaBootComponentsEndPoint.java
  sofa-boot-project/sofa-boot-autoconfigure/src/test/java/com/alipay/sofa/autoconfigure/test/runtime/SofaRuntimePropertiesTest.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/SofaRuntimeProperties.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/configure/SofaRuntimeConfigurationProperties.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/ext/component/ExtensionComponent.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/ext/component/ExtensionPointComponent.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/ext/spring/ExtensionFactoryBean.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/ext/spring/ExtensionPointFactoryBean.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/component/ReferenceComponent.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/component/ServiceComponent.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/helper/ReferenceRegisterHelper.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spi/component/AbstractComponent.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spi/component/ComponentDefinitionInfo.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/ReferenceAnnotationBeanPostProcessor.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/factory/ReferenceFactoryBean.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/factory/ServiceFactoryBean.java
  sofa-boot-project/sofa-boot-parent/pom.xml
  sofa-boot-project/sofa-boot-starters/runtime-sofa-boot-starter/pom.xml
Labels: cla:yes, size/L

#1119 Add rpc actuator configuration
  sofa-boot-project/sofa-boot-actuator-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/SofaBootRpcProperties.java
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/SofaRpcAutoConfiguration.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/context/RpcStartApplicationListener.java
Labels: size/M, cla:yes

#1120 SofaEventHandlerTest use mockito
  sofa-boot-project/sofa-boot-autoconfigure/pom.xml
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/SofaEventHandlerTest.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  sofa-boot-project/sofa-boot-core/startup-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-parent/pom.xml
Labels: cla:yes, size/L

#1121 reference component health check support more deails when failed
  sofa-boot-project/sofa-boot-autoconfigure/src/test/java/com/alipay/sofa/autoconfigure/test/runtime/SofaRuntimePropertiesTest.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/SofaRuntimeProperties.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/configure/SofaRuntimeConfigurationProperties.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/component/ReferenceComponent.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spi/component/ComponentDefinitionInfo.java
Labels: question, size/M, cla:yes

#1122 Fix rpc grpc tests
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/src/test/java/com/alipay/sofa/boot/gradle/plugin/DependencyManagementPluginActionIntegrationTests.java
  sofa-boot-project/sofaboot-dependencies/pom.xml
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/main/resources/spring/test_all.xml
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/test/java/com/alipay/sofa/smoke/tests/rpc/boot/SofaBootRpcApplicationTests.java
Labels: bug, cla:yes, size/L

#1125 upgrade javassit version to 3.29.2-GA ,rpc smoke tests use javassist
  sofa-boot-project/sofaboot-dependencies/pom.xml
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/main/resources/META-INF/sofa-rpc/rpc-config.json
Labels: cla:yes, size/XS

#1126 4.0.0
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/logging/LogEnvironmentPostProcessor.java
Labels: cla:yes, size/XS

#1124 fix(test): update library causing flaky test behavior
  sofa-boot-project/sofa-boot-parent/pom.xml
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/src/test/java/com/alipay/sofa/common/boot/logging/test/DefaultLevelTest.java
Labels: bug, cla:yes, size/XS, First-time contributor

#1130 refactor aware processor
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/runtime/SofaRuntimeAutoConfiguration.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/ClientFactoryAnnotationBeanPostProcessor.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/ExtensionClientBeanPostProcessor.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/JvmFilterPostProcessor.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/RuntimeContextBeanFactoryPostProcessor.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/RuntimeShutdownAwarePostProcessor.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/SofaRuntimeAwareProcessor.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/SofaRuntimeContextAwareProcessor.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/SofaRuntimeAwareProcessorTest.java
Labels: cla:yes, size/XL

#1129 Support custom healthheck and healthindicator config
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/HealthCheckProperties.java
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/HealthCheckerConfig.java
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/HealthCheckerProcessor.java
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/HealthIndicatorProcessor.java
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/test/java/com/alipay/sofa/healthcheck/test/HealthCheckerConfigTest.java
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/test/java/com/alipay/sofa/healthcheck/test/bean/DiskHealthChecker.java
Labels: cla:yes, size/L

#1131 Update springboot 3.0.5
  pom.xml
Labels: cla:yes

#1132 Support repeatable @SofaServices annotation
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/api/annotation/SofaService.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/api/annotation/SofaServices.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/ServiceBeanFactoryPostProcessor.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/RepeatableSofaServiceTest.java
Labels: cla:yes, size/L

#1128 Update dubbo 3.1.8 and curator 4.3.0
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/pom.xml
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/main/resources/spring/test_all.xml
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/test/java/com/alipay/sofa/smoke/tests/rpc/boot/SofaBootRpcApplicationTests.java
Labels: cla:yes, size/L

#1127 use ApplicationStartup static root application startup
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/startup/SofaStartupAutoConfiguration.java
  sofa-boot-project/sofa-boot-autoconfigure/src/test/java/com/alipay/sofa/autoconfigure/test/startup/SofaStartupAutoConfigurationTest.java
  sofa-boot-project/sofa-boot-core/startup-sofa-boot/src/main/java/com/alipay/sofa/startup/StartupProperties.java
  sofa-boot-project/sofa-boot-core/startup-sofa-boot/src/main/java/com/alipay/sofa/startup/StartupReporter.java
  sofa-boot-project/sofa-boot-core/startup-sofa-boot/src/main/java/com/alipay/sofa/startup/stage/BeanCostBeanPostProcessor.java
  sofa-boot-project/sofa-boot-core/startup-sofa-boot/src/main/java/com/alipay/sofa/startup/stage/StartupContextRefreshedListener.java
  sofa-boot-project/sofa-boot-core/startup-sofa-boot/src/main/java/com/alipay/sofa/startup/stage/StartupSpringApplicationRunListener.java
  sofa-boot-project/sofa-boot-core/startup-sofa-boot/src/test/java/com/alipay/sofa/startup/test/SimpleStartupReporterTest.java
  sofa-boot-project/sofa-boot-core/startup-sofa-boot/src/test/java/com/alipay/sofa/startup/test/configuration/SofaStartupAutoConfiguration.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/startup/BaseStat.java
Labels: cla:yes, size/L

#1134 modify RuntimeContextBeanFactoryPostProcessor field modifier protected
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/RuntimeContextBeanFactoryPostProcessor.java
Labels: cla:yes, size/S

#1138 remote springboot startup endpoint
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/constant/SofaBootConstants.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/env/EnvironmentCustomizer.java
Labels: size/M, cla:yes

#1139 Update guice 5.1.0
  pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
  sofa-boot-tests/pom.xml
Labels: cla:yes, size/S
