Repository sofastack/sofa-boot, pull requests merged in 2023-09, with the labels that each got.

#1243 release_3.20.0
  pom.xml
Labels: cla:yes, size/XS

#1248 Update sofa hessian to 3.5.1 and sofa ark to 2.2.3
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/XS

#1247 Fix the issue where @SofaService annotation cannot set a custom threa…
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/converter/RpcBindingConverter.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spi/service/BindingConverterContext.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/ServiceBeanFactoryPostProcessor.java
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/main/java/com/alipay/sofa/smoke/tests/rpc/boot/bean/threadpool/ThreadPoolServiceAnnotationImpl.java
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/main/resources/spring/test_all.xml
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/test/java/com/alipay/sofa/smoke/tests/rpc/boot/SofaBootRpcApplicationTests.java
Labels: bug, size/M, cla:yes

#1246 Avoid SofaConfigSourceSupportListener duplicate register configs
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/listener/SofaConfigSourceSupportListener.java
Labels: cla:yes, size/XS

#1249 Update SpringBoot to 3.1.3
  pom.xml
Labels: cla:yes, size/XS

#1250 Update 3.21.0-SNAPSHOT
  pom.xml
Labels: cla:yes, size/XS

#1252 Merge 1247
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/converter/RpcBindingConverter.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/SofaBootRpcAllTest.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/bean/threadpool/ThreadPoolServiceAnnotationImpl.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/resources/spring/test_all.xml
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spi/service/BindingConverterContext.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/ServiceBeanFactoryPostProcessor.java
Labels: size/M, cla:yes

#1253 Update springboot 3.1.4
  pom.xml
Labels: cla:yes, size/XS
