Repository sofastack/sofa-boot, pull requests merged in 2023-02, with the labels that each got.

#1063 rpc auto configuration test case
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/RestFilterConfiguration.java
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/SofaRpcAutoConfiguration.java
  sofa-boot-project/sofa-boot-autoconfigure/src/test/java/com/alipay/sofa/boot/autoconfigure/rpc/SofaRpcAutoConfigurationTests.java
Labels: cla:yes, size/L

#1068 remore feign configuration
  sofa-boot-project/sofa-boot-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/bean/SofaParameterNameDiscoverer.java
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-runtime/src/test/java/com/alipay/sofa/smoke/tests/runtime/proxy/TestProxyConfiguration.java
Labels: cla:yes, size/XS

#1071 Update springboot 2.7.8
  pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/XS

#1076 rpc smoke tests modify
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/test/java/com/alipay/sofa/rpc/boot/test/config/DefaultTracingTest.java
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/test/java/com/alipay/sofa/rpc/boot/test/config/SofaRpcLoggerLevelConfigTest.java
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/test/java/com/alipay/sofa/rpc/boot/test/readiness/ReadinessTest.java
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/test/java/com/alipay/sofa/rpc/boot/test/reference/ReferenceTest.java
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/test/java/com/alipay/sofa/tests/rpc/boot/SofaBootRpcApplicationTests.java
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/test/java/com/alipay/sofa/tests/rpc/mesh/MeshTest.java
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/test/java/com/alipay/sofa/tests/rpc/misc/XsdTimeoutTest.java
Labels: size/M, cla:yes

#1078 Fix components end point
  sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/components/SofaBootComponentsEndPoint.java
Labels: bug, cla:yes, size/XS

#1083 4.0.0
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/SwaggerConfiguration.java
  sofa-boot-project/sofa-boot-autoconfigure/src/test/java/com/alipay/sofa/boot/autoconfigure/rpc/SofaRpcAutoConfigurationTests.java
  sofa-boot-project/sofa-boot/pom.xml
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/Initializer/SwitchableApplicationContextInitializer.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/annotation/condition/ConditionalOnSwitch.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/annotation/condition/OnSwitchCondition.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/listener/SwitchableApplicationListener.java
  sofa-boot-project/sofa-boot/src/main/resources/sofa-boot/scenes/function.properties
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/main/resources/sofa-boot/scenes/function-test.properties
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/test/java/com/alipay/sofa/smoke/tests/rpc/SofaRpcLoggerLevelConfigTests.java
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/src/test/java/com/alipay/sofa/smoke/tests/rpc/boot/SofaBootRpcApplicationTests.java
Labels: cla:yes, size/L

#1094 add test module
  sofa-boot-project/sofa-boot-actuator/src/test/java/com/alipay/sofa/boot/actuator/health/HealthCheckerProcessorTests.java
  sofa-boot-project/sofa-boot-core/pom.xml
  sofa-boot-project/sofa-boot-core/test-sofa-boot/pom.xml
  sofa-boot-project/sofa-boot-starters/pom.xml
  sofa-boot-project/sofa-boot-starters/test-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/test-sofa-boot-starter/src/main/resources/META-INF/MANIFEST.MF
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/util/LogOutPutUtils.java
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/L

#1096 Add test module
  sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/health/HealthCheckerProcessor.java
  sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/health/HealthIndicatorProcessor.java
  sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/health/ReadinessCheckCallbackProcessor.java
  sofa-boot-project/sofa-boot-actuator/src/test/java/com/alipay/sofa/boot/actuator/health/HealthIndicatorProcessorTests.java
  sofa-boot-project/sofa-boot-actuator/src/test/java/com/alipay/sofa/boot/actuator/health/ReadinessCheckCallbackProcessorTest.java
  sofa-boot-project/sofa-boot-actuator/src/test/java/com/alipay/sofa/boot/actuator/health/ReadinessCheckListenerTests.java
Labels: cla:yes, size/L

#1098 fix_readiness_thredpool_configuration
  sofa-boot-project/sofa-boot-actuator-autoconfigure/src/main/java/com/alipay/sofa/boot/actuator/autoconfigure/health/ReadinessAutoConfiguration.java
  sofa-boot-project/sofa-boot-actuator-autoconfigure/src/test/java/com/alipay/sofa/boot/actuator/autoconfigure/health/ReadinessAutoConfigurationTests.java
  sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/health/ReadinessCheckListener.java
Labels: bug, size/M, cla:yes

#1099 update local env
  sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/startup/StartupEndPoint.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/impl/StandardSofaRuntimeManager.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/startup/StartupReporter.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/startup/StartupSpringApplicationRunListener.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/util/SofaBootEnvUtils.java
  sofa-boot-project/sofaboot-dependencies/pom.xml
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-tracer/src/test/java/com/alipay/sofa/smoke/tests/tracer/TracerDataSourceTests.java
Labels: size/M, cla:yes

#1101 Fix error properties
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/tracer/rabbitmq/RabbitMqAutoConfiguration.java
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/tracer/rocketmq/RocketMqAutoConfiguration.java
Labels: bug, cla:yes, size/XS
