Repository sofastack/sofa-boot, pull requests merged in 2023-04, with the labels that each got.

#1140 add unit tests for util
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/ext/spring/parser/AbstractExtBeanDefinitionParser.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/ext/spring/parser/ExtensionPointBeanDefinitionParser.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/util/XmlParserUtils.java
  sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/util/BeanDefinitionUtilTests.java
  sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/util/ClassLoaderContextUtilsTests.java
  sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/util/LogOutPutUtilsTests.java
  sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/util/ServiceLoaderUtilsTests.java
  sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/util/SofaBootEnvUtilsTests.java
Labels: cla:yes, size/L

#1141 Add sofa boot ut
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/annotation/AnnotationWrapper.java
  sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/lisener/SwitchableApplicationListenerTests.java
  sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/log/SofaBootLoggerFactoryTests.java
  sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/logging/LogEnvironmentPreparingListenerTests.java
Labels: cla:yes, size/L

#1148 Add jacoco module
  sofa-boot-project/sofa-boot-parent/pom.xml
  sofa-boot-tests/pom.xml
  sofa-boot-tests/sofa-boot-jacoco-report/pom.xml
Labels: cla:yes, size/L

#1151 Add codecov configs
  .github/workflows/maven.yml
Labels: cla:yes, size/XS

#1152 Add ark tests
  sofa-boot-project/sofa-boot-core/ark-sofa-boot/src/main/java/com/alipay/sofa/boot/ark/SofaRuntimeContainer.java
  sofa-boot-project/sofa-boot-core/ark-sofa-boot/src/main/java/com/alipay/sofa/boot/ark/invoke/DynamicJvmServiceInvoker.java
  sofa-boot-project/sofa-boot-core/ark-sofa-boot/src/main/java/com/alipay/sofa/boot/ark/invoke/DynamicJvmServiceProxyFinder.java
  sofa-boot-project/sofa-boot-core/ark-sofa-boot/src/test/java/com/alipay/sofa/boot/ark/MockBiz.java
  sofa-boot-project/sofa-boot-core/ark-sofa-boot/src/test/java/com/alipay/sofa/boot/ark/MockBizManagerService.java
  sofa-boot-project/sofa-boot-core/ark-sofa-boot/src/test/java/com/alipay/sofa/boot/ark/SofaRuntimeContainerTests.java
  sofa-boot-project/sofa-boot-core/ark-sofa-boot/src/test/java/com/alipay/sofa/boot/ark/handler/AfterBizStartupEventHandlerTests.java
  sofa-boot-project/sofa-boot-core/ark-sofa-boot/src/test/java/com/alipay/sofa/boot/ark/handler/FinishStartupEventHandlerTests.java
  sofa-boot-project/sofa-boot-core/ark-sofa-boot/src/test/java/com/alipay/sofa/boot/ark/handler/SofaBizHealthCheckEventHandlerTests.java
  sofa-boot-project/sofa-boot-core/ark-sofa-boot/src/test/java/com/alipay/sofa/boot/ark/handler/SofaBizUninstallEventHandlerTests.java
  sofa-boot-project/sofa-boot-core/ark-sofa-boot/src/test/java/com/alipay/sofa/boot/ark/invoke/ArkDynamicServiceProxyManagerTests.java
  sofa-boot-project/sofa-boot-core/ark-sofa-boot/src/test/java/com/alipay/sofa/boot/ark/invoke/DynamicJvmServiceInvokerTests.java
  sofa-boot-project/sofa-boot-core/ark-sofa-boot/src/test/java/com/alipay/sofa/boot/ark/invoke/DynamicJvmServiceProxyFinderTests.java
  sofa-boot-project/sofa-boot-core/ark-sofa-boot/src/test/java/com/alipay/sofa/boot/ark/invoke/JvmServiceTargetHabitatTests.java
  sofa-boot-project/sofa-boot-core/ark-sofa-boot/src/test/java/com/alipay/sofa/boot/ark/sample/Pojo.java
  sofa-boot-project/sofa-boot-core/ark-sofa-boot/src/test/java/com/alipay/sofa/boot/ark/sample/SampleService.java
  sofa-boot-project/sofa-boot-core/ark-sofa-boot/src/test/java/com/alipay/sofa/boot/ark/sample/SampleServiceImpl.java
Labels: cla:yes, size/XXL

#1154 Add isle module uts
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/boot/isle/loader/DynamicSpringContextLoader.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/boot/isle/spring/SofaModuleContextLifecycle.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/boot/isle/stage/ModuleLogOutputStage.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/boot/isle/stage/SpringContextInstallStage.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/boot/isle/ApplicationRuntimeModelTests.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/boot/isle/MockDeploymentDescriptor.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/boot/isle/deployment/AbstractDeploymentDescriptorTests.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/boot/isle/deployment/DefaultModuleDeploymentValidatorTests.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/boot/isle/deployment/DependencyTreeEntryTests.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/boot/isle/deployment/DependencyTreeTests.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/boot/isle/deployment/DeployRegistryTests.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/boot/isle/deployment/DeploymentDescriptorConfigurationTests.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/boot/isle/deployment/FileDeploymentDescriptorTests.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/boot/isle/deployment/JarDeploymentDescriptorTests.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/boot/isle/loader/DynamicSpringContextLoaderTests.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/boot/isle/profile/DefaultSofaModuleProfileCheckerTests.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/boot/isle/spring/SofaModuleContextLifecycleTests.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/boot/isle/stage/DefaultPipelineContextTests.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/boot/isle/stage/ModelCreatingStageTests.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/boot/isle/stage/ModuleLogOutputStageTests.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/boot/isle/stage/SpringContextInstallStageTests.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/resources/META-INF/spring/spring1.xml
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/resources/META-INF/spring/spring2.xml
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/resources/module.jar
Labels: cla:yes, size/XXL

#1155 fix BeanPostProcessorOrderTest testShutDownHookReordered
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/BeanPostProcessorOrderTest.java
Labels: bug, cla:yes, size/XS

#1156 use FactoryBean.OBJECT_TYPE_ATTRIBUTE to support ReferenceFactoryBean…
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/ServiceBeanFactoryPostProcessor.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/parser/ReferenceDefinitionParser.java
Labels: cla:yes, size/S

#1149 add sofa-boot-jacoco-report
  .github/workflows/maven.yml
  sofa-boot-project/pom.xml
  sofa-boot-project/sofa-boot-actuator-autoconfigure/src/test/java/com/alipay/sofa/actuator/autoconfigure/test/StartupHealthCheckStageConfigurationTest.java
  sofa-boot-project/sofa-boot-autoconfigure/src/test/java/com/alipay/sofa/autoconfigure/test/startup/SofaStartupIsleAutoConfigurationTest.java
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/test/java/com/alipay/sofa/healthcheck/test/HealthCheckerProcessorParallelTest.java
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/test/java/com/alipay/sofa/healthcheck/test/HealthIndicatorCheckProcessorParallelTest.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/DuplicateModuleAddCustomJarTest.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/FailModuleAddCustomJarTest.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/FailModuleWithParallelAddCustomJarTest.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/test/java/com/alipay/sofa/isle/test/SingletonProcessorAddCustomJarTest.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/SofaRuntimeProperties.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/ComponentManagerShutdownTest.java
  sofa-boot-project/sofa-boot-core/startup-sofa-boot/src/test/java/com/alipay/sofa/startup/test/SimpleStartupReporterTest.java
  sofa-boot-project/sofa-boot-jacoco-report/pom.xml
  sofa-boot-project/sofa-boot-parent/pom.xml
  sofa-boot-project/sofa-boot-starters/log-sofa-boot-starter/pom.xml
  sofa-boot-project/sofa-boot-starters/tracer-sofa-boot-starter/src/test/java/com/alipay/sofa/tracer/boot/springcloud/FeignClientTest.java
  sofa-boot-project/sofa-boot/pom.xml
Labels: cla:yes, size/L
