Repository sofastack/sofa-boot, pull requests merged in 2023-08, with the labels that each got.

#1207 Upadte springboot 3.1.2
  pom.xml
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/build.gradle
  sofa-boot-project/sofa-boot-tools/sofa-boot-gradle-plugin/pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/S

#1216 Update ci config
  .github/workflows/maven.yml
Labels: cla:yes, size/XS

#1219 update ci config
  .github/workflows/maven.yml
Labels: cla:yes, size/XS

#1220 Remove search strategy
  sofa-boot-project/sofa-boot-actuator-autoconfigure/src/main/java/com/alipay/sofa/boot/actuator/autoconfigure/startup/StartupHealthCheckStageConfiguration.java
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/startup/SofaStartupIsleAutoConfiguration.java
  sofa-boot-project/sofa-boot-core/startup-sofa-boot/src/test/java/com/alipay/sofa/startup/test/configuration/SofaStartupHealthCheckAutoConfiguration.java
  sofa-boot-project/sofa-boot-core/startup-sofa-boot/src/test/java/com/alipay/sofa/startup/test/configuration/SofaStartupIsleAutoConfiguration.java
Labels: cla:yes, size/S

#1217 update sofa tracer 3.1.3
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/XS

#1221 Support compatibility
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/compatibility/CompatibilityVerifierApplicationContextInitializer.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/resources/META-INF/spring.factories
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/compatibility/CompatibilityVerifierApplicationContextInitializerTest.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/compatibility/TestCompatibilityVerifier.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/resources/META-INF/spring.factories
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/compatibility/AbstractJarVersionVerifier.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/compatibility/AbstractSwitchableCompatibilityVerifier.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/compatibility/CompatibilityNotMetException.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/compatibility/CompatibilityPredicate.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/compatibility/CompatibilityVerifier.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/compatibility/CompositeCompatibilityVerifier.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/compatibility/VerificationResult.java
  sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/test/compatibility/AbstractJarVersionVerifierTest.java
  sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/test/compatibility/AbstractSwitchableCompatibilityVerifierTest.java
  sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/test/compatibility/CompositeCompatibilityVerifierTest.java
Labels: cla:yes, size/XL

#1222 update error logs
  sofa-boot-project/sofa-boot/src/main/resources/sofa-boot/log-codes.properties
Labels: cla:yes, size/XS

#1223 Update compatibility not met message
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/compatibility/CompatibilityVerifierApplicationContextInitializerTest.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/compatibility/AbstractJarVersionVerifier.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/compatibility/CompatibilityNotMetException.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/compatibility/CompositeCompatibilityVerifier.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/compatibility/VerificationResult.java
  sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/test/compatibility/AbstractSwitchableCompatibilityVerifierTest.java
  sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/test/compatibility/CompositeCompatibilityVerifierTest.java
Labels: size/M, cla:yes

#1225 ensure threadlocal object remove after use
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/isle/stage/ModuleLogOutputStage.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/factory/BeanLoadCostBeanFactory.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/invoke/DynamicJvmServiceProxyFinder.java
Labels: cla:yes, size/S

#1227 Cherry pick issues form 3.x
  pom.xml
  sofa-boot-project/sofa-boot-actuator-autoconfigure/src/main/java/com/alipay/sofa/boot/actuator/autoconfigure/health/ReadinessAutoConfiguration.java
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/SofaRpcAutoConfiguration.java
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/runtime/SofaRuntimeProperties.java
  sofa-boot-project/sofa-boot-autoconfigure/src/test/java/com/alipay/sofa/boot/autoconfigure/runtime/SofaRuntimeAutoConfigurationTests.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/component/ServiceComponent.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spi/component/SofaRuntimeContext.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/service/component/ServiceComponentTests.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/compatibility/AbstractJarVersionVerifier.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/compatibility/AbstractSwitchableCompatibilityVerifier.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/compatibility/CompatibilityNotMetException.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/compatibility/CompatibilityPredicate.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/compatibility/CompatibilityVerifier.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/compatibility/CompatibilityVerifierApplicationContextInitializer.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/compatibility/CompositeCompatibilityVerifier.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/compatibility/VerificationResult.java
  sofa-boot-project/sofa-boot/src/main/resources/META-INF/spring.factories
  sofa-boot-project/sofa-boot/src/main/resources/sofa-boot/log-codes.properties
  sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/compatibility/AbstractJarVersionVerifierTests.java
  sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/compatibility/AbstractSwitchableCompatibilityVerifierTests.java
  sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/compatibility/CompatibilityVerifierApplicationContextInitializerTests.java
  sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/compatibility/CompositeCompatibilityVerifierTests.java
  sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/compatibility/TestCompatibilityVerifier.java
  sofa-boot-project/sofa-boot/src/test/resources/META-INF/spring.factories
Labels: cla:yes, size/XL

#1230 Merge 4.0.1 to 4.1.0
  sofa-boot-project/sofa-boot-core/ark-sofa-boot/src/main/java/com/alipay/sofa/boot/ark/SofaRuntimeContainer.java
  sofa-boot-project/sofa-boot-core/ark-sofa-boot/src/main/java/com/alipay/sofa/boot/ark/invoke/DynamicJvmServiceInvoker.java
  sofa-boot-project/sofa-boot-core/ark-sofa-boot/src/test/java/com/alipay/sofa/boot/ark/SofaRuntimeContainerTests.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/ServiceBeanFactoryPostProcessor.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/bean/SofaParameterNameDiscoverer.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/spring/bean/SofaParameterNameDiscovererTests.java
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/context/SofaSpringContextSupport.java
  sofa-boot-project/sofa-boot/src/test/java/com/alipay/sofa/boot/context/SofaSpringContextSupportTests.java
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: size/M, cla:yes

#1231 add_protobuf_dependencies
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/S

#1233 Init interface type canonical name to avoid multi reflection
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/invoke/DynamicJvmServiceProxyFinder.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/component/AbstractContract.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spi/binding/Contract.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/SofaEventHandlerTest.java
Labels: cla:yes, size/S

#1235 Init interface type canonical name to avoid multi reflection (#1233)
  sofa-boot-project/sofa-boot-core/ark-sofa-boot/src/main/java/com/alipay/sofa/boot/ark/invoke/DynamicJvmServiceProxyFinder.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/component/AbstractContract.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spi/binding/Contract.java
Labels: cla:yes, size/S

#1236 revert dependency change for sofa-boot-core
  sofa-boot-project/sofa-boot-core/pom.xml
Labels: cla:yes, size/XS

#1238 Update sofa stack component versions
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/XS

#1240 Merge 4.0.1 to master
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/XS

#1241 Add mock inject error code
  sofa-boot-project/sofa-boot-core/test-sofa-boot/src/main/java/com/alipay/sofa/test/mock/injector/InjectorMockTestExecutionListener.java
  sofa-boot-project/sofa-boot-core/test-sofa-boot/src/main/java/com/alipay/sofa/test/mock/injector/resolver/BeanInjectorResolver.java
  sofa-boot-project/sofa-boot-core/test-sofa-boot/src/main/java/com/alipay/sofa/test/mock/injector/resolver/BeanInjectorStub.java
  sofa-boot-project/sofa-boot/src/main/resources/sofa-boot/log-codes.properties
Labels: size/M, cla:yes

#1242 Add mock inject error code (#1241)
  sofa-boot-project/sofa-boot-core/test-sofa-boot/src/main/java/com/alipay/sofa/test/mock/injector/InjectorMockTestExecutionListener.java
  sofa-boot-project/sofa-boot-core/test-sofa-boot/src/main/java/com/alipay/sofa/test/mock/injector/resolver/BeanInjectorResolver.java
  sofa-boot-project/sofa-boot-core/test-sofa-boot/src/main/java/com/alipay/sofa/test/mock/injector/resolver/BeanInjectorStub.java
  sofa-boot-project/sofa-boot/src/main/resources/sofa-boot/log-codes.properties
Labels: size/M, cla:yes
