Repository sofastack/sofa-boot, pull requests merged in 2024-05, with the labels that each got.

#1315 Fix readme for build status
  README.md
  README_ZH.md
Labels: bug, cla:yes, size/XS

#1314 Fix typos
  sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/health/ReadinessCheckCallbackProcessor.java
Labels: bug, cla:yes, size/XS

#1318 Fix build status
  .github/workflows/maven.yml
  README.md
  README_ZH.md
Labels: bug, cla:yes, size/XS

#1316 Fix lazyinit value transfer problem
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/ServiceBeanFactoryPostProcessor.java
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-runtime/src/test/java/com/alipay/sofa/smoke/tests/runtime/spring/SofaBeanLazyInitTests.java
Labels: bug, cla:yes, size/L

#1317 Fix lazyinit value transfer problem
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/ServiceBeanFactoryPostProcessor.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/SofaServiceAndReferenceTest.java
Labels: bug, size/M, cla:yes

#1320 Fix beans information lost parentId
  sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/beans/IsleBeansEndpoint.java
Labels: bug, cla:yes, size/S

#1319 Fix beans information lost parentId
  sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/beans/IsleBeansEndpoint.java
Labels: bug, cla:yes, size/S

#1322 Release 3.23.0
  pom.xml
Labels: cla:yes, size/XS

#1323 update dependencies
  pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/S

#1324 Fix sofaruntime manager destroy whitout shutdown
  sofa-boot-project/sofa-boot-core/ark-sofa-boot/src/main/java/com/alipay/sofa/boot/ark/SofaRuntimeContainer.java
  sofa-boot-project/sofa-boot-core/ark-sofa-boot/src/main/java/com/alipay/sofa/boot/ark/handler/SofaBizUninstallEventHandler.java
  sofa-boot-project/sofa-boot-core/ark-sofa-boot/src/test/java/com/alipay/sofa/boot/ark/SofaRuntimeContainerTests.java
  sofa-boot-project/sofa-boot-core/ark-sofa-boot/src/test/java/com/alipay/sofa/boot/ark/handler/SofaBizUninstallEventHandlerTests.java
Labels: bug, size/M, cla:yes

#1325 application startup update register order
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/startup/StartupSpringApplicationRunListener.java
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-boot/src/test/java/com/alipay/sofa/smoke/tests/boot/StartupApplicationStartupTests.java
Labels: size/M, cla:yes

#1326 Update Spring Boot 3.2.6
  pom.xml
Labels: cla:yes, size/XS

#1327 add runnable/callable class in async invoke method
  sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/health/HealthCheckerProcessor.java
  sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/health/HealthIndicatorProcessor.java
  sofa-boot-project/sofa-boot-core/isle-sofa-boot/src/main/java/com/alipay/sofa/boot/isle/stage/SpringContextInstallStage.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/async/AsyncInitializeBeanMethodInvoker.java
Labels: cla:yes, size/L
