Repository sofastack/sofa-boot, pull requests merged in 2024-04, with the labels that each got.

#1303 update springboot 2.7.18
  pom.xml
Labels: cla:yes, size/XS

#1274 Add Code Scan Action
  .github/workflows/cloud_code_scan.yml
Labels: cla:yes, size/S, First-time contributor

#1307 Upgrade github action version to v4
  .github/workflows/maven.yml
  .github/workflows/release.yml
Labels: cla:yes, size/S, First-time contributor

#1306 Support mac M1(osx-aarch_64) compile and test
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/XS, First-time contributor

#1305 Support mac M1(osx-aarch_64) compile and test
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/pom.xml
  sofa-boot-tests/sofa-boot-smoke-tests/sofa-boot-smoke-tests-rpc/pom.xml
Labels: cla:yes, cla:no, size/XS, First-time contributor

#1308 Upgrade github action version to v4
  .github/workflows/maven.yml
  .github/workflows/release.yml
Labels: cla:yes, size/S, First-time contributor

#1309 Fix readiness health check list mistake in parallel checking scenario
  sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/HealthCheckerProcessor.java
Labels: bug, cla:yes, size/XS, First-time contributor

#1310 Fix readiness health check list mistake in parallel checking scenario
  sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/health/HealthCheckerProcessor.java
Labels: bug, cla:yes, size/XS, First-time contributor

#1304 avoid concurrent problem in JvmFilterHolder
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/filter/JvmFilterHolder.java
Labels: cla:yes, size/XS

#1311 increase StartupSpringApplicationRunListener order
  sofa-boot-project/sofa-boot-core/startup-sofa-boot/src/main/java/com/alipay/sofa/startup/stage/StartupSpringApplicationRunListener.java
Labels: cla:yes, size/XS

#1313 Update community contact way
  README.md
Labels: cla:yes, size/S
