Repository sofastack/sofa-boot, pull requests merged in 2024-12, with the labels that each got.

#1353 Upgrade spring boot version to 3.3.6
  pom.xml
Labels: cla:yes, size/XS

#1354 fix 并行调用多例Bean时 annotationWrapper 导致的线程安全问题
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spring/ReferenceAnnotationBeanPostProcessor.java
Labels: bug, size/M, cla:yes

#1355 4.4.1-SNAPSHOT
  pom.xml
Labels: cla:yes, size/XS

#1357 Fix export module name
  sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/util/ModuleUtil.java
Labels: bug, cla:yes, size/XS

#1356 Upgrade rpc all version to 5.13.2
  sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/SofaRpcAutoConfiguration.java
  sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/context/SofaBootRpcStartListener.java
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/S

#1358 Upgrade spring boot version to 3.3.7
  pom.xml
Labels: cla:yes, size/XS
