Repository sofastack/sofa-boot, pull requests merged in 2025-04, with the labels that each got.

#1360 manualReadinessCallbackMap remove classLoader when uninstall biz component
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/SofaRuntimeProperties.java
Labels: question, cla:yes, size/XS

#1362 Fix StandardSofaRuntimeManager mem leak
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/client/impl/ClientFactoryImpl.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/component/impl/StandardSofaRuntimeManager.java
  sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spi/client/ClientFactoryInternal.java
Labels: bug, cla:yes, size/S

#1348 Update pom.xml
  sofa-boot-project/sofaboot-dependencies/pom.xml
Labels: cla:yes, size/XS, First-time contributor
